export enum WAS_OVERALL_TIMMING {
  TITLE = "TITLE",
  LOADING = "LOADING",
  MAIN_MAP = "MAIN_MAP",
  MAIN_AREA = "MAIN_AREA",
  ENDING = "ENDING",
}

export enum WAS_AREA_TIMMING {
  SELECT_MOVE = "SELECT_MOVE",
  EXPLORE = "EXPLORE",
  SELECT_CONSUME_ITEM = "SELECT_CONSUME_ITEM",
  USE_CONSUME_ITEM = "USE_CONSUME_ITEM",
  SELECT_PERSUADE_ITEM = "SELECT_PERSUADE_ITEM",
  USE_PERSUADE_ITEM = "USE_PERSUADE_ITEM",
  FACE = "FACE",
  BATTLE_SELECT_MOVE = "BATTLE_SELECT_MOVE",
  BATTLE_ATTACK = "BATTLE_ATTACK",
  BATTLE_SELECT_SKILL = "BATTLE_SELECT_SKILL",
  BATTLE_USE_SKILL = "BATTLE_USE_SKILL",
  BATTLE_SELECT_ITEM = "BATTLE_SELECT_ITEM",
  BATTLE_USE_ITEM = "BATTLE_USE_ITEM",
}

export enum WAS_EVENT_TIMMING {
  OPENING = 0,
  AFTER_OPENING1 = 1,
  AFTER_OPENING2 = 2,
  AFTER_CLEAR_CAVE = 3,
  AFTER_CLEAR_SEA = 4,
  AFTER_CLEAR_VILLAGE = 5,
  AFTER_CLEAR_MOUNTAIN = 6,
  AFTER_CLEAR_ALL_AREA = 7,
  AFTER_CLEAR_KINGDOM_CASTLE = 8,
}
