import { COLOR, GOUColor } from "@/composables/types/GOUColor";

const TBH_DEFAULT_GAME_DISPLAY_WIDTH = 600;
const TBH_DEFAULT_GAME_DISPLAY_HEIGHT = 600;

const TBH_SOUND_ROOT_PATH = "/games/tbh/sounds/";
const TBH_IMAGE_ROOT_PATH = "/games/tbh/images/";

const TBH_MESSAGEFRAME_BACKGROUND_COLOR = new GOUColor(COLOR.SHALLOW_BLUE, 0.9);
const TBH_MESSAGEFRAME_BORDER_COLOR = new GOUColor(COLOR.BLACK, 0.8);

export {
  TBH_DEFAULT_GAME_DISPLAY_WIDTH,
  TBH_DEFAULT_GAME_DISPLAY_HEIGHT,
  TBH_SOUND_ROOT_PATH,
  TBH_IMAGE_ROOT_PATH,
  TBH_MESSAGEFRAME_BACKGROUND_COLOR,
  TBH_MESSAGEFRAME_BORDER_COLOR,
};
