const COMMON_SOUND_ROOT_PATH = "/games/commons/sounds/";

export const WIL_SOUND_DEFINES: { [key: string]: string } = {
  // SE
  SE_FIGHTING: COMMON_SOUND_ROOT_PATH + "effects/double_slash1.mp3",
  SE_GARD: COMMON_SOUND_ROOT_PATH + "effects/gard1.mp3",
  SE_MONSTER: COMMON_SOUND_ROOT_PATH + "effects/monster1.mp3",
  SE_EXPLOSION: COMMON_SOUND_ROOT_PATH + "effects/explosion1.mp3",
  SE_FALL_DOWN: COMMON_SOUND_ROOT_PATH + "effects/fall_down.mp3",
  SE_SYSTEM1: COMMON_SOUND_ROOT_PATH + "systems/system1.mp3",
  SE_SLASH: COMMON_SOUND_ROOT_PATH + "effects/slash1.mp3",
  SE_CROSS_SLASH: COMMON_SOUND_ROOT_PATH + "effects/double_slash2.mp3",
  SE_BLOW1: COMMON_SOUND_ROOT_PATH + "effects/blow1.mp3",
  SE_BLOW2: COMMON_SOUND_ROOT_PATH + "effects/blow2.mp3",
  SE_BLOW3: COMMON_SOUND_ROOT_PATH + "effects/blow3.mp3",
  SE_BLOW4: COMMON_SOUND_ROOT_PATH + "effects/blow4.mp3",
  SE_ARROW: COMMON_SOUND_ROOT_PATH + "effects/arrow1.mp3",
  SE_FIRE1: COMMON_SOUND_ROOT_PATH + "effects/fire1.mp3",
  SE_FIRE2: COMMON_SOUND_ROOT_PATH + "effects/fire2.mp3",
  SE_HEAL1: COMMON_SOUND_ROOT_PATH + "effects/heal1.mp3",
  SE_HEAL2: COMMON_SOUND_ROOT_PATH + "effects/heal2.mp3",
  SE_HEAL3: COMMON_SOUND_ROOT_PATH + "effects/heal3.mp3",
  SE_HOLY1: COMMON_SOUND_ROOT_PATH + "effects/holy1.mp3",
  SE_HOLY2: COMMON_SOUND_ROOT_PATH + "effects/holy2.mp3",
  SE_BEAM1: COMMON_SOUND_ROOT_PATH + "effects/beam1.mp3",
  SE_DARK1: COMMON_SOUND_ROOT_PATH + "effects/dark1.mp3",
  SE_DARK2: COMMON_SOUND_ROOT_PATH + "effects/dark2.mp3",
  SE_ICE1: COMMON_SOUND_ROOT_PATH + "effects/ice1.mp3",
  SE_POISON1: COMMON_SOUND_ROOT_PATH + "effects/poison1.mp3",
  SE_RAIN1: COMMON_SOUND_ROOT_PATH + "effects/rain1.mp3",
  SE_STONE1: COMMON_SOUND_ROOT_PATH + "effects/stone1.mp3",
  SE_THUNDER1: COMMON_SOUND_ROOT_PATH + "effects/thunder1.mp3",
  SE_THUNDER2: COMMON_SOUND_ROOT_PATH + "effects/thunder4.mp3",
  SE_WARP: COMMON_SOUND_ROOT_PATH + "effects/warp.mp3",
  SE_WATER1: COMMON_SOUND_ROOT_PATH + "effects/water1.mp3",
  SE_WIND1: COMMON_SOUND_ROOT_PATH + "effects/wind1.mp3",
  SE_WIND2: COMMON_SOUND_ROOT_PATH + "effects/wind2.mp3",

  // BGM
  BGM_VILLAGE1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_village09.mp3",
  BGM_PINCH1: COMMON_SOUND_ROOT_PATH + "bgm/maou_bgm_neorock47.mp3",
  BGM_PINCH2: COMMON_SOUND_ROOT_PATH + "bgm/dovasyndrome_12449.mp3",
  BGM_PINCH3: COMMON_SOUND_ROOT_PATH + "bgm/youfulca_face_the_fear.mp3",
  BGM_HOLY_CASLE1: COMMON_SOUND_ROOT_PATH + "bgm/maou_bgm_orchestra06.mp3",
  BGM_HOLY_CASLE2: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_castle02.mp3",
  BGM_DEPLOY1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_rock28.mp3",
  BGM_DEPLOY2: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_boss03.mp3",
  BGM_DEPLOY3: COMMON_SOUND_ROOT_PATH + "bgm/dovasyndrome_11161.mp3",
  BGM_BATTLE1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_battle36.mp3",
  BGM_BATTLE2: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_battle27.mp3",
  BGM_BATTLE3: COMMON_SOUND_ROOT_PATH + "bgm/youfulca_YAMATO.mp3",
  BGM_BATTLE4: COMMON_SOUND_ROOT_PATH + "bgm/youfulca_tower_of_despair.mp3",
  BGM_BATTLE5:
    COMMON_SOUND_ROOT_PATH + "bgm/youfulca_battle_with_darklord_2013.mp3",
  BGM_BATTLE_WIN1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_jingle01.mp3",
  BGM_BATTLE_LOSE: COMMON_SOUND_ROOT_PATH + "bgm/maou_bgm_orchestra26.mp3",
  BGM_BATTLE_LOSE_SHORT:
    COMMON_SOUND_ROOT_PATH + "bgm/maou_bgm_orchestra26_short.mp3",
  BGM_TRAINING1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_field11.mp3",
  BGM_SNOWSTORM: COMMON_SOUND_ROOT_PATH + "bgm/soundeffect_lab_snowstorm.mp3",
  BGM_ICE_LAND1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_castle03.mp3",
  BGM_WINDBLOW: COMMON_SOUND_ROOT_PATH + "bgm/soundeffect_lab_windblow.mp3",
  BGM_STORM_LAND1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_dangeon04b.mp3",
  BGM_FIRE_LAND1: COMMON_SOUND_ROOT_PATH + "bgm/dovasyndrome_19413.mp3",
  BGM_FIRE: COMMON_SOUND_ROOT_PATH + "bgm/soundeffect_lab_fire.mp3",
  BGM_NIGHT: COMMON_SOUND_ROOT_PATH + "bgm/maou_bgm_healing10.mp3",
  BGM_HOPE: COMMON_SOUND_ROOT_PATH + "bgm/dovasyndrome_13024.mp3",
  BGM_ENDING: COMMON_SOUND_ROOT_PATH + "bgm/dovasyndrome_18833.mp3",
};
