const COMMON_SOUND_ROOT_PATH = "/games/commons/sounds/";

export const WIL_SOUND_DEFINES: { [key: string]: string } = {
  // SE
  SE_FIGHTING: COMMON_SOUND_ROOT_PATH + "effects/double_slash1.mp3",
  SE_GARD: COMMON_SOUND_ROOT_PATH + "effects/gard1.mp3",
  SE_MONSTER: COMMON_SOUND_ROOT_PATH + "effects/monster1.mp3",
  SE_EXPLOSION: COMMON_SOUND_ROOT_PATH + "effects/explosion1.mp3",
  SE_SYSTEM1: COMMON_SOUND_ROOT_PATH + "systems/system1.mp3",
  SE_SLASH: COMMON_SOUND_ROOT_PATH + "effects/slash1.mp3",
  SE_CROSS_SLASH: COMMON_SOUND_ROOT_PATH + "effects/double_slash2.mp3",
  SE_BLOW1: COMMON_SOUND_ROOT_PATH + "effects/blow1.mp3",
  SE_BLOW2: COMMON_SOUND_ROOT_PATH + "effects/blow2.mp3",
  SE_BLOW3: COMMON_SOUND_ROOT_PATH + "effects/blow3.mp3",
  SE_BLOW4: COMMON_SOUND_ROOT_PATH + "effects/blow4.mp3",
  SE_ARROW: COMMON_SOUND_ROOT_PATH + "effects/arrow1.mp3",
  SE_HEAL1: COMMON_SOUND_ROOT_PATH + "effects/heal1.mp3",
  SE_HEAL2: COMMON_SOUND_ROOT_PATH + "effects/heal2.mp3",
  SE_HEAL3: COMMON_SOUND_ROOT_PATH + "effects/heal3.mp3",
  SE_HOLY1: COMMON_SOUND_ROOT_PATH + "effects/holy1.mp3",
  SE_BEAM1: COMMON_SOUND_ROOT_PATH + "effects/beam1.mp3",
  SE_DARK1: COMMON_SOUND_ROOT_PATH + "effects/dark1.mp3",
  SE_ICE1: COMMON_SOUND_ROOT_PATH + "effects/ice1.mp3",
  SE_POISON1: COMMON_SOUND_ROOT_PATH + "effects/poison1.mp3",
  SE_RAIN1: COMMON_SOUND_ROOT_PATH + "effects/rain1.mp3",
  SE_STONE1: COMMON_SOUND_ROOT_PATH + "effects/stone1.mp3",
  SE_THUNDER1: COMMON_SOUND_ROOT_PATH + "effects/thunder1.mp3",
  SE_THUNDER2: COMMON_SOUND_ROOT_PATH + "effects/thunder4.mp3",
  SE_WATER1: COMMON_SOUND_ROOT_PATH + "effects/water1.mp3",
  SE_WIND1: COMMON_SOUND_ROOT_PATH + "effects/wind1.mp3",

  // BGM
  BGM_VILLAGE_1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_village09.mp3",
  BGM_PINCH_1: COMMON_SOUND_ROOT_PATH + "bgm/maou_bgm_neorock47.mp3",
  BGM_HOLY_CASLE_1: COMMON_SOUND_ROOT_PATH + "bgm/maou_bgm_orchestra06.mp3",
  BGM_DEPLOY_1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_rock28.mp3",
  BGM_DEPLOY_2: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_boss03.mp3",
  BGM_BATTLE_1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_battle36.mp3",
  BGM_BATTLE_2: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_battle27.mp3",
  BGM_BATTLE_WIN1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_jingle01.mp3",
  BGM_BATTLE_WIN2: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_castle03.mp3",
  BGM_BATTLE_LOSE:
    COMMON_SOUND_ROOT_PATH + "bgm/maou_bgm_orchestra26_short.mp3",
  BGM_TRAINING_1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_field11.mp3",
  BGM_SNOWSTORM: COMMON_SOUND_ROOT_PATH + "bgm/soundeffect_lab_snowstorm.mp3",
  BGM_ICE_LAND_1: COMMON_SOUND_ROOT_PATH + "bgm/maou_game_castle03.mp3",
};
