import { WIL_IMAGE_ID } from "@/composables/games/wil/enums/image";
import { WIL_SOUND_ID } from "@/composables/games/wil/enums/sound";

export type WilTalkDefine = Array<{
  talker?: string;
  background?: WIL_IMAGE_ID;
  message?: Array<string>;
  sound?: WIL_SOUND_ID;
  bgm?: WIL_SOUND_ID;
  left?: WIL_IMAGE_ID;
  right?: WIL_IMAGE_ID;
}>;

/**
 * メインイベントの会話イベント定義
 */
export const WIL_MAIN_TALK_DEFINES: {
  [key: string]: WilTalkDefine;
} = {
  CHAPTER_1_1: [
    {
      message: ["かつてこの世界には、魔物が蔓延っていた。"],
    },
    {
      message: [
        "魔物は魔王の力によって生み出され、魔王の意思によって人間を襲っていた。",
        "人々は魔王と魔物たちに怯えながら暮らしていた。",
      ],
    },
    {
      message: ["だがある日、聖剣を持った勇者が現れ、魔王を倒した。"],
    },
    {
      message: [
        "魔王の体は五体に分割して封印され、五つの国で管理されることとなった。",
        "右腕は焔(ほむら)の国、左腕は氷(こおり)の国、右足は嵐(あらし)の国、左足は金(こがね)の国、そして胴体と頭部は聖(ひじり)の国に、代々受け継がれてきた。",
      ],
    },
    {
      message: [
        "勇者は魔王が封印されている限り、魔物は減り、平和が続くだろうと語ったそうだ。",
        "実際、ここ数百年で魔物の目撃情報はほとんどない。",
      ],
    },
    {
      message: [
        "だが、世界の覇権を手にしようとしている焔の国が、魔王の力を利用するためにその封印の一部を解いてしまった。",
        "封印の一部が解かれたことにより、平和だった世界に再び魔物が現れ、各所で暴れだしているのであった。",
      ],
    },
    {
      talker: "村長",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      message: [
        "ヒカル、今年の収穫もよろしく頼むよ。",
        "若い男はヒカル一人だからね。頼りにしてるよ。",
      ],
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: ["はい。任せてください。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: ["（俺はヒカル。聖の国の端の田舎村に住む、ただの農民だ。）"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "村長",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: [
        "そうだ、最近妙なうめき声が聞こえるらしい。",
        "魔物なんて、私が子供のころには見なくなっていたが、一応気をつけてな。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: [
        "わかりました。",
        "でも、村に何かあったら、俺に任せてください。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "村長",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: ["さすが、勇敢だ。", "頼りにしているよ。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      message: ["その日の夕方"],
    },
    {
      talker: "村の子供",
      sound: WIL_SOUND_ID.SE_MONSTER,
      bgm: WIL_SOUND_ID.BGM_PINCH_1,
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["きゃー！"],
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SHADOW,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["あれは、魔物...？", "少なくとも人間ではないな...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["...危ない！"],
      sound: WIL_SOUND_ID.SE_MONSTER,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SHADOW,
    },
    {
      message: [""],
      sound: WIL_SOUND_ID.SE_FIGHTING,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["はぁはぁ...。", "もう大丈夫。早く逃げるんだ！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "村の子供",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["うん。ありがとう！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "（子供の手前、ああ言ったけど、かなり厳しいな...。このままじゃ村が...。）",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      sound: WIL_SOUND_ID.SE_MONSTER,
      message: ["...！？", "しまった！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SHADOW,
    },
    {
      talker: "？？？",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      sound: WIL_SOUND_ID.SE_GARD,
      message: [
        "おっと、危ない。",
        "よくここまで持ちこたえたな。",
        "もう大丈夫だ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "俺は聖騎士団の隊長、ザーグ！",
        "今からこの村は聖騎士団が守る！",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "聖騎士団！？",
        "帝都を守っているはずの聖騎士団がなんでこんなところに！？",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["そんなことより、君も早く逃げなさい。", "ここは危険だ！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["（逃げるか...？でも、この村は...。）"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "すみません、俺にも戦わせてください！",
        "足手まといにはならないようにします。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["この村を、守りたいんです！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "...いい目だ、気に入った！",
        "本来は許可できないが、俺は強いからな。何かあっても守ってやる。",
        "側から離れるなよ！",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["...はい！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      sound: WIL_SOUND_ID.SE_MONSTER,
      message: ["くるぞ！構えろ！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
  ],
  CHAPTER_1_2: [
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      message: ["ふう、なんとか凌いだかな...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["それにしても君、やるなぁ。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["ありがとうございます。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "こんなことを頼むのもなんだが、聖騎士団に入ってみないか？",
        "君ほどの強さなら、歓迎するよ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "せっかくのお誘いですが、またいつこの村が襲われるか分からないので...。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "そうか、村を守るためか...。",
        "だが、それならなおさら聖騎士団に入った方がいい。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["それは、どういう...？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "実は、魔物が急に現れだしたのには理由があってね。",
        "最近、焔の国が魔王の封印の一部を解いてしまったようなんだ。",
        "漏れ出した魔王の魔力から、魔物が生まれ出しているらしい。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["そんなことが...。", "でも、どうして焔の国はそんなことを？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "魔王の力を利用して、他の国を支配し、世界の王になろうとしてるのさ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "おっと、少し喋りすぎてしまった。",
        "ま、とにかく焔の国を何とかしないと、この村どころか聖の国自体が危ないんだよ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["なるほど...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "さっきの戦いぶり、君の力には期待しているんだ。",
        "そうだ、村が心配なら駐屯兵を配置するように手配しておこう。",
        "徴兵でもない限りは常駐できるだろうし、今の君が守るよりは安全だろう。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["兵を配置していただけるんですか！？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["（ここまで言ってくれるんだ。あんまり気は乗らないけど...。）"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["分かりました。聖騎士団に入ります。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "よし！よく言ってくれた！",
        "じゃあ、いろいろと準備があるから、一週間後に帝都に来てくれ。",
        "楽しみにしているよ！",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "...行っちゃった。",
        "一週間後か...。",
        "少しでも役に立てるように、特訓しておくか。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
  ],
  CHAPTER_1_3: [
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      bgm: WIL_SOUND_ID.BGM_HOLY_CASLE_1,
      message: ["はあ、帝都は広いなあ。えーと、聖騎士団に会うには...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["おや、そこにいるのは、この間の少年じゃないか。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["あなたはあの時の...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: [
        "俺は聖騎士団隊長、ザーグ！...って前にも自己紹介したっけか？",
        "えーと、君は...",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["ヒカルです。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["ヒカル君、待っていたよ。", "じゃあ早速入団試験を始めようか。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["え、入団試験？", "そんなの聞いてないんですが...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: [
        "スカウトしたとはいえ、改めて力を確認しておきたいからね。",
        "なに、難しい試験じゃないさ。",
        "聖騎士団相手の三対三の模擬戦に勝ってくれれば良い。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: [
        "もちろん聖騎士団側は手加減するさ。",
        "君の味方二人は聖騎士団の中から見繕うから、好きに使ってくれ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["試験って、人格とか知能の確認とかは？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: [
        "筆記試験とか倫理試験とかも考えたけど、面倒くさくてね。",
        "剣を交えれば大体わかるだろう。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["（この人、こんなに脳筋だったのか...。）"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["早速始めようか。", "彼らが君の味方だよ。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "騎士兵",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["よろしく。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
    },
    {
      talker: "魔導兵",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["よろしく。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["よろしくお願いします。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
    },
  ],
  CHAPTER_1_4: [
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["はぁはぁ、なんとか勝てた...。"],
      bgm: WIL_SOUND_ID.BGM_HOLY_CASLE_1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: [
        "まさか、本当に勝てるとは思ってなかったよ。",
        "やはり君は俺の期待に応えてくれそうだね。",
        "これからよろしく！",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["なんか、疲れた...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "魔導兵",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: [
        "君、隊長にそそのかされて来たんでしょ？",
        "これから大変だよ...。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["え？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
    },
    {
      talker: "騎士兵",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: [
        "もう分かってると思うけど、あの人勢いだけで動いてるところあるから...。",
        "まあ、一緒に頑張ろう。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["えぇ...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_KINGDOM,
      message: ["さあ、さっそく特訓だ！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
  ],
  CHAPTER_2_1: [
    {
      sound: WIL_SOUND_ID.SE_FIGHTING,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: [
        "ヒカル、やるなぁ。聖騎士団に入ってまだそんなに経ってないのに、大したもんだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "ヒカル",
      message: ["ありがとうございます。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "魔導兵",
      message: ["お前、入りたての頃はザーグさんにしごかれてたもんな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["お前こそ、ザーグさんとの訓練で泣きべそかいてたくせに。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "魔導兵",
      message: ["かいてないし。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["でも、ここまで強くなれたのもザーグさんのおかげだよな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "魔導兵",
      message: ["まあそれはある。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["二人とも、ザーグさんを慕ってるんですね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵&魔導兵",
      message: ["いや？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: [
        "ザーグさん、見ての通りめちゃくちゃだから、振り回されてばっかりだよ。この前も...",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["訓練中に私語とは余裕だな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "魔導兵",
      message: ["あ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: [
        "いやいや、ちょっと休憩してただけですよ。ヒカル、そろそろ再開しようか！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["いや、話があるからそのままでいい。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      bgm: WIL_SOUND_ID.BGM_PINCH_1,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "来週、皇帝陛下が氷の国に出向くことになった。",
        "当然我々聖騎士団も護衛として同行することになるから、準備しておくように。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["陛下自ら氷の国に行くなんて、どうしたんですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "なんでも、焔の国の勢力に対抗するために、氷の国と同盟を組む予定らしい。平和のため、絶対に成立させなければならない同盟だから、陛下が直々に交渉しに行くらしい。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["なるほど。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "帝都の守護のために全員で行くわけにはいかないが、めったにない大仕事だし、ヒカルも来るか？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["いいんですか？ぜひ行かせてください！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["いい返事だ。決まりだ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["改めて言うが、出発は来週だ。各自訓練に勤しむこと。以上！"],
    },
  ],
  CHAPTER_2_2: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_KINGDOM,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["そろそろ出発だ。準備はいいか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_KINGDOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["はい！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_KINGDOM,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["長時間の移動になるけど、みんなよろしく頼むよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["（あれが皇帝陛下か...。優しそうな人だな。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_KINGDOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["あれ？君は初めて見る顔だね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: [
        "あ、はい！つい最近入団したヒカルと申します！",
        "命に代えても陛下をお守りします！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_KINGDOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["頼りにしているよ、ヒカル君。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["ヒカル、陛下と話せるなんてラッキーだったな！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "ヒカル",
      message: [
        "緊張しました...。",
        "流石に目の前にすると気が引き締まりますね。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: [
        "固くなって肝心なときに動けないなんてやめてくれよ！",
        "まあ氷の国までの道のりは整備されてるし、何か起こるなんてそうそうないだろうけどな！",
      ],
    },
    { message: ["数時間後"] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      bgm: WIL_SOUND_ID.BGM_SNOWSTORM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["なんか、寒くなってきましたね...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "氷の国は年中雪で覆われている国だからな。近づくほど寒くなるぞ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["あれ、なんか人影みたいなのが見えませんか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["まさか。こんなところに人間がいるわけ..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      sound: WIL_SOUND_ID.SE_MONSTER,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["...あれは魔物だ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "全員、戦闘態勢に入れ！万が一にも皇帝陛下に危害がないようにしろ！",
      ],
    },
  ],
  CHAPTER_2_3: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      bgm: WIL_SOUND_ID.BGM_SNOWSTORM,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["はぁはぁ、みんな、無事か！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "魔導兵",
      message: ["魔導兵の一部が毒に侵されて氷の国まで持つかどうか...。"],
    },

    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["騎士兵も大多数が負傷してます...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "くそっ、次に襲われたら厳しいな...。氷の国までもう少しだというのに！",
        "しかし、対処しきれない数じゃなかったはずだが...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: [
        "この寒さだと動きが鈍ってしまいますからね...。しかも雪で視界も悪い...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "慣れない環境での戦闘は苦しかったか...。帰ったら鍛え直しだな。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: [
        "これ、結構まずいんじゃないですか？引いたとしても安全に帰れる保証はないし...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "そうだな...。幸い氷の国は治癒魔法に長けている。多少強引にでも突っ切るしかないか。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      sound: WIL_SOUND_ID.SE_MONSTER,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["...ザーグさん！危ない！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      sound: WIL_SOUND_ID.SE_FIGHTING,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル&ザーグ",
      message: ["！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      talker: "守護兵",
      message: ["大丈夫、か？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      talker: "ザーグ",
      message: ["あなたは？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      talker: "守護兵",
      message: [
        "俺たち、氷の守護者。ここ、氷の国の領地。客人、安全に出迎える。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      talker: "補助兵",
      message: ["けが人が多いね。治してやろう。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      message: ["補助兵は癒しの水を発動した。"],
      sound: WIL_SOUND_ID.SE_HEAL1,
    },
    { message: [""] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      bgm: WIL_SOUND_ID.BGM_ICE_LAND_1,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "助かりました。",
        "本当にありがとうございます。",
        "私は聖騎士団の隊長ザーグです。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      talker: "守護兵",
      message: ["話、聞いてる。王のもと、行く。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      talker: "ザーグ",
      message: ["ありがとうございます。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "ヒカル、俺は陛下に付き添ってフロリア王、フロリア様のところまで行ってくる。その間、みんなをよろしく。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["分かりました。お気をつけて。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: [
        "それにしても、危なかったな...。氷の国の人たちが優しくてよかった。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "？？？",
      message: [
        "ふーん、これが聖の国の精鋭？あれくらいの魔物相手で壊滅状態なんて、随分危うい近衛兵ね。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["えーと、あなたは？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "？？？",
      message: ["あなた、一般兵でしょ？そんなのに名乗る名前はないわ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["はぁ...。", "えーと、もしかして王女様とかですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "氷の国の王女",
      message: ["へぇ、一般兵の分際でよくわかったわね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: [
        "身なりがとても綺麗だったので。",
        "（あと、なんか偉そうだったし...。）",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "氷の国の王女",
      message: ["ふーん。ところであなたたち、同盟を結びに来たんでしたっけ？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["そうですけど。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "氷の国の王女",
      message: [
        "お父様はお優しいけど、さすがにこの状況を見てなんの条件もなく同盟を結ぶとは思えないわ。どこの国だって、弱い国とは手を組みたくないもの。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: [
        "ちょっと言いすぎじゃないですか。確かに聖騎士団はボロボロですが、それは慣れない環境だったからというだけで...",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ザーグ",
      message: ["そこまでだ、ヒカル。", "レイナ様、うちの兵士が失礼しました。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "まあいいわ。あなたがここにいるってことは、対談は終わったようね。私ももう行くわ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["ザーグさん...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ザーグ",
      message: [
        "ヒカル、相手は一国の王女様だ。発言には気をつけろよ。",
        "それに、レイナ様の言っていたことは事実だ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["それはわかってますが...。でも、それじゃあ同盟は...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ザーグ",
      message: [
        "言っただろ、これの同盟は絶対に成立させなければならない。",
        "そこで陛下は、聖の国の力を示すために氷の国との模擬戦を申し出た。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["模擬戦...ですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ザーグ",
      message: [
        "模擬戦に勝てば聖の国の力を認め、同盟を組んでくれるよう交渉してくださったのだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ザーグ",
      message: [
        "模擬戦は少数で行うらしいんだが、さっきの戦闘で負傷者が多い。ヒカル、お前の力も貸してくれ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["はい！任せてください！"],
    },
    { message: ["一時間後"] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      talker: "フロリア王",
      message: ["では、これから氷の国と聖の国の模擬戦を始める。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      talker: "フロリア王",
      message: ["レイナ、手は抜くなよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      talker: "レイナ",
      message: ["もちろんです。お父様。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["（あの王女様も出るのか。絶対に負けられない！）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["王女様が相手か。手加減が大変そうだな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "おい、油断するなよ。あれでも氷の国の軍隊を仕切ってるんだ。俺と同じくらいの実力だと思ったほうがいい。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["まじすか...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["皆さん、来ます！"],
    },
  ],
  CHAPTER_2_4: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      bgm: WIL_SOUND_ID.BGM_ICE_LAND_1,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["...っく！この私が負けるなんて...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "フロリア王",
      message: ["レイナ！大丈夫か！？貴様ら、よくも娘を！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["（じゃあどうすりゃ良かったんだよ...。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["あなた、思ったより強いのね...。見直したわ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["はあ、それはどうも。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "名乗る名がないなんて言って悪かったわ。",
        "私はレイナ。この国の王女よ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: [
        "ヒカルです。聖騎士団に所属しています。",
        "こちらこそ、失礼な態度をとってすみませんでした。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["あれくらい気にしてないわ。それよりも..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "お父様、この方々の強さは証明されました。おとなしく同盟を受け入れましょう。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "フロリア王",
      message: [
        "ムムム。しかし...。",
        "（同盟を結んでしまえば、戦いが増える...。戦いが増えればレイナが危険な目にあってしまう...。）",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "模擬戦で負ければ同盟を受け入れるという条件をのみ、真剣勝負で負けたのは我々です。仕方がありません。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "氷の国の王",
      message: ["わ、わかった。では、同盟を..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      sound: WIL_SOUND_ID.SE_STONE1,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "フロリア王",
      message: ["！？", "何じゃこの音は！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["西のほうから聞こえましたわ！", "様子を見に行きましょう。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ザーグ",
      message: ["嫌な予感がする。俺たちも行くぞ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      bgm: WIL_SOUND_ID.BGM_PINCH_1,
      sound: WIL_SOUND_ID.SE_MONSTER,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "レイナ",
      message: ["何...あいつ...？", "尋常じゃない魔力を感じるわ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "皇帝",
      message: [
        "人型の強力な魔物...もしかして魔人というやつではないだろうか。昔、古文書で読んだことがある。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "フロリア王",
      message: ["なんでもよい！守護兵たちよ、やつを追い払うのじゃ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "守護兵",
      message: ["御意。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      sound: WIL_SOUND_ID.SE_EXPLOSION,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "守護兵",
      message: ["無念...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "フロリア王",
      message: ["まさか、我が国の兵が、あんなにあっさり...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "ヒカル",
      message: ["こっちに向かって来てませんか！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "レイナ",
      message: [
        "冗談じゃないわ！あんなのに来られたらこの国はひとたまりもないわ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "フロリア王",
      message: [
        "何ということだ！",
        "同盟でもなんでも受け入れるから、なんとかしてくれ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "ザーグ",
      message: ["言われなくても、なんとかしなきゃ我々も危ないですから...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "ばらばらに戦っても勝機が薄れるだけだわ。",
        "私たちで聖騎士団を全力でサポートしましょう！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "守護兵",
      message: ["次こそは。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "補助兵",
      message: ["任せな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["くるぞ！総員、配置につけ！"],
    },
  ],
  CHAPTER_2_5: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      bgm: WIL_SOUND_ID.BGM_SNOWSTORM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "ザーグ",
      message: ["くそっ、どんだけタフなんだ、こいつは！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "レイナ",
      message: ["まずいわ、もうみんなボロボロよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "ヒカル",
      message: ["（このまま戦っても状況は悪くなる一方...。一か八か...。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "ヒカル",
      message: [
        "提案なんですが、あの顔の宝石みたいなのを全員で攻撃してみませんか？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["そんなことして何になるのよ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: [
        "あいつの魔法は、すべてあの宝石から放出されているように見えます。",
        "なので、あれさえ壊せば攻撃も回復もされなくなるんじゃないかと・",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["なるほど。理にはかなってるな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "だとして、あいつに近づいてそこまでのダメージを与えるなんて、どうやってやるのよ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: [
        "俺が囮になります。",
        "あいつの気を引いているうちに、ザーグさんとレイナさんで一気に攻撃してください。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "そんな危険な役割、新兵のお前にやらせられるか！",
        "囮なら俺がやる！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: [
        "あいつの属性は水。大ダメージを与えるなら雷属性の技を使えるザーグさんの方が適任です。",
        "大丈夫です。守りに専念すれば避けきれない攻撃じゃない。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["...信じるぞ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["任せてください。", "...行ってきます！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["レイナ様、俺の合図で一斉に畳みかけましょう。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "レイナ",
      message: ["分かったわ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      sound: WIL_SOUND_ID.SE_MONSTER,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      sound: WIL_SOUND_ID.SE_ICE1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      talker: "ザーグ",
      message: ["今だ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      sound: WIL_SOUND_ID.SE_THUNDER2,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_ICE_DEMON,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      sound: WIL_SOUND_ID.SE_MONSTER,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      talker: "フロリア王",
      message: ["倒した...のか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["やったの？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      bgm: WIL_SOUND_ID.BGM_BATTLE_WIN2,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["勝ったぞ！魔人を倒した！！", "ヒカル、お前のおかげだ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: [
        "ははは...。ザーグさんの力あってこそです...。上手くいって良かった...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      talker: "フロリア王",
      message: [
        "しかし、既にあれほどまでの魔物が現れるまで事態進んでいるのか...。",
        "これはもう、わしの我儘を通すわけにはいくまい。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      talker: "皇帝",
      message: ["ということは...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      talker: "フロリア王",
      message: [
        "氷の国は聖の国と同盟を結ぼう！",
        "共に焔の国を抑え、再び魔物のいない平和な世界を取り戻すのじゃ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_FIELD,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      talker: "皇帝",
      message: ["ありがとうございます！", "みんな、よくやってくれた！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      message: [
        "こうして、聖の国は氷の国と同盟を結び、これから始まる焔の国との戦いへと準備を進めるのであった。",
      ],
    },
  ],
};

/**
 * サブイベントの会話イベント定義
 */
export const WIL_SUB_TALK_DEFINES: {
  [key: string]: WilTalkDefine;
} = {
  HERO_1: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["聖騎士団の訓練"],
    },
    {
      talker: "ヒカル",
      message: ["なるほど、聖騎士団の特訓は大きく分けて5種類あるのか。"],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      message: [
        "侵攻訓練は攻めること、防衛訓練は守ることに焦点を当てた訓練で、",
        "移動訓練は体力をつけて素早く行動できるようになるための訓練。",
      ],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      message: [
        "魔導学習では新しい魔法を覚えられて、",
        "打込稽古では剣技を学んだりできるみたいだ。",
      ],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      message: [
        "バランスよく鍛えるか、集中して鍛えるか、自分に合った鍛え方をしないとな...。",
      ],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      message: [
        "そういえば、魔法や剣技は素質がないと使えないって話をどこかで聞いたな。",
        "剣技はともかく、俺って魔法の素質あるのかな...？",
      ],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
  ],
  HERO_2: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["戦闘と陣形"],
    },
    {
      talker: "ヒカル",
      message: ["前にザーグさんと戦ったとき、魔物が陣形をとっていたな。"],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      message: ["戦う時の位置って何か意味があるのかな？"],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      message: [
        "ああ、当然だけど、目の前に味方がいたら剣では攻撃できないか。",
        "逆に、敵の前に別の敵がいたら攻撃が届かないな。",
      ],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      message: [
        "そういえば、ザーグさんが使っていた雷の技は、近くにいると感電しそうだったな。",
        "もしかして、技によって攻撃が影響する範囲が変わったりするとか？",
      ],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      message: ["戦う時の立ち位置、意外と重要かもな...。"],
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_VILLAGE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
  ],
  HERO_3: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["ヒカルと騎士兵"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["はぁ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["ヒカル、気合入ってるな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "ヒカル",
      message: ["お疲れ様です。新しい技を試したくて。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["ヒカルって、どこかで剣術とか習ってたのか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "ヒカル",
      message: ["いえ、特には。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: [
        "まじか。筋良すぎだろ。",
        "俺なんて、子供のころから帝都の剣術教室に通ってたのに。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "ヒカル",
      message: ["剣術教室なんてあるんですね。それで太刀筋が綺麗なのか...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["え、俺の太刀筋って綺麗？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "ヒカル",
      message: ["はい。なんというか、無駄がないって感じがします。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: [
        "そうかそうか！剣術のことなら、いつでも俺に聞いてくれよ！はっはっは！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "ヒカル",
      message: ["なんか、調子のいい人だなぁ...。"],
    },
  ],
  HERO_4: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["ヒカルと魔導兵"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: [
        "えーと、魔法には属性があって、雷属性は水属性に強く、土属性に弱いのか。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: ["ヒカル、勉強熱心だな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "ヒカル",
      message: [
        "お疲れ様です。",
        "魔法って初めて覚えたんですけど、奥が深いですね。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: [
        "そうだろう。あの脳筋のザーグさんでさえ魔法を勉強してるんだぞ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "ヒカル",
      message: ["それはどういう自慢ですか...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: [
        "解釈はお任せします。",
        "ヒカルは魔法の良さはどこにあると思う？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "ヒカル",
      message: [
        "えーと、何もないところから攻撃を生み出せるところ...とかですか？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: ["あっさ。", "別に無から生み出してるわけじゃないんだよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: [
        "魔法は生物が生まれながらに持つ『魔素』をもとに生成されるのは知ってるよね？つまり無から生まれているように見えて実は元となる物質があるわけだ。まあ物質といっても見ることも触ることもできないから無といっても過言ではないんだけど。とはいえ『魔素をもとにした生成技術』が魔法である以上、無から攻撃を生みだしているとは言えないよね。そもそも...",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "ヒカル",
      message: ["（癖のある人だなぁ...。）"],
    },
  ],
  HERO_5: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["ヒカルとザーグ"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["ヒカル、聖騎士団には慣れたか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["はい、皆さんとても良くしてくれるので、だいぶ慣れてきました。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["それは良かった。そうだ、たまには俺と試合でもしてみるか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["いいんですか！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["もちろんだ、遠慮はいらない。全力でかかってこい！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["はい！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      sound: WIL_SOUND_ID.SE_FIGHTING,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["はあはぁ。やっぱりザーグさんは強いですね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "いやいや、入団数日でこれだけ戦えるんだから、ヒカルもたいしたもんだよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: [
        "ありがとうございます。ザーグさんはどうやって強くなったんですか？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "よく聞いてくれた。俺は強くなるために三つのことを意識しているんだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["三つのこと？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["まず第一に訓練。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["（あ、これってまさか...。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["二に訓練。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["三四に訓練、五に訓練！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["全部訓練なうえに、五つに増えてるじゃないですか！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["はっはっは。細かいことは気にするな！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["あの人、よく隊長になれたな...。"],
    },
  ],
  HOLY_KNIGHTS_LEADER_1: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["隊長の仕事"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "今日の訓練はここまで！",
        "俺は隊長業務があるから、後片付けよろしく！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["あー疲れた。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: ["もう動けん。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: [
        "ザーグさん、隊長業務って言ってましたけど、何やってるんでしょうか？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: [
        "あーあれね。隊長になると、俺たちみたいな下の人間だけじゃなくて、上と話したりするらしいよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "ヒカル",
      message: ["上っていうと...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: [
        "主に皇帝陛下だな。陛下の外出予定を聞いて護衛の準備をしたりとか、聖騎士団の予算の調整したりとか色々話してるみたいだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "ヒカル",
      message: ["そんなこともやるんですね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["ああ見えて意外と頭脳労働もしてるんだよなぁ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      bgm: WIL_SOUND_ID.BGM_HOLY_CASLE_1,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "陛下！来年度の聖騎士団の予算ですが、今年度と同じでよいですか！？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "えーと、聖騎士団には頑張ってもらってるし、焔の国との決戦もあるだろうから、予算は増やしたほうが良いんじゃないかな？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: [
        "なるほど！じゃあ増やしましょう！それと、陛下の外出予定ですが...",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "まとめといたから護衛よろしくね。あと、この日は氷の国までの遠出になるから、いつもより多めに人を割いてもらえると助かるよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["わかりました！できるだけ人員を割くようにします！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["...分かってると思うけど、国を守るための人は残しておいてね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      message: ["...皇帝陛下が有能だった。"],
    },
  ],
  HOLY_KNIGHTS_LEADER_2: [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["ザーグと騎士兵"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      bgm: WIL_SOUND_ID.BGM_VILLAGE_1,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["おい、ちょっと手伝ってくれないか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["何ですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["新技を思いついてね。試しに受けてみてほしいんだ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["げ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["なーに手加減はするよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["ほんとですかぁ？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["部下を痛めつけるようなことするわけないじゃないか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["...ちょっとだけですよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      sound: WIL_SOUND_ID.SE_EXPLOSION,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["...手加減の意味知ってますか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "悪い悪い！",
        "ちょっと気合が入りすぎてしまった！まあ、いい練習になったよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["次はこの技なんだけど...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["もう勘弁してください。"],
    },
  ],
};

/**
 * チュートリアル定義
 */
export const WIL_TUTORIAL_DEFINES: {
  [key: string]: WilTalkDefine;
} = {
  BATTLE_SET_CHARACTER_1: [
    {
      sound: WIL_SOUND_ID.SE_SYSTEM1,
      message: ["戦闘システムの説明を行います。"],
    },
    {
      message: [
        "戦闘が始まる前に、まずはキャラクターを配置します。",
        "技や魔法によって届く距離が変わったり、影響範囲が変わったりしますので、そのことを考慮して配置を行ってください。",
      ],
    },
    {
      message: [
        "キャラクターを配置できるのは青色のマスです。",
        "配置したいマスを選択した後に、画面下部から配置するキャラクターを選択してください。",
      ],
    },
  ],
  BATTLE_SET_CHARACTER_2: [
    {
      message: [
        "配置できるキャラクターは最大5人までです。",
        "全てのキャラクターを配置したら、配置終了ボタンを押して戦闘を開始してください。",
      ],
    },
  ],
  BATTLE_START: [
    {
      message: [
        "戦闘では『スタック数』というものが少ない順にターンが回ってきます。",
        "『スタック数』は次に行動できるまでのターン数のようなもので、何らかの行動を行うと貯まります。",
      ],
    },
    {
      message: [
        "スタック数はキャラクターごとに確認できますが、キャラクターの行動順のみを確認したい場合は画面左上に表示されますので、そちらをご確認ください。",
        "黄色のキャラクターが今のターンキャラクターで、右にいるほど早く行動できるキャラクターになります。",
      ],
    },
  ],
  BATTLE_SELECT_MOVE: [
    {
      message: [
        "ターンが来たキャラクターは『移動』、『技・魔法』、『ターンスキップ』のいずれかの行動をとることができます。",
      ],
    },
    {
      message: [
        "『移動』は自分フィールド内で任意の場所に移動できます。",
        "敵の攻撃を見て、今の配置が適していないと思った場合に使用して下さい。",
        "『移動』の際は、キャラクターの敏捷力が高いほどスタック数が少なくなります。",
      ],
    },
    {
      message: [
        "『技・魔法』では敵に攻撃したり、補助魔法を使用することができます。",
        "技ごとに溜まるスタック数が決まっており、強い技ほどスタック数が貯まりやすい、つまり行動する回数が少なくなる仕組みとなっています。",
        "なお、本ゲームにおいて『通常攻撃』というコマンドはなく、すべて『技・魔法』として扱っております。",
      ],
    },
    {
      message: [
        "『ターンスキップ』を行うと、次のキャラクターの行動後に行動処理を決め直すことができます。",
        "他のキャラクターが行動してから改めて行動を決めたい場合にご利用ください。",
      ],
    },
    {
      message: [
        "戦闘システムについての説明は以上となります。",
        "ご武運をお祈り申し上げます。",
      ],
    },
  ],
  TRAINING: [
    {
      sound: WIL_SOUND_ID.SE_SYSTEM1,
      message: ["訓練システムの説明を行います。"],
    },
    {
      message: [
        "訓練メニューは五つあり、一つの訓練メニューにつき一人のキャラクターを選択することができます。",
        "訓練によって、上がりやすいステータス値や技・魔法の習得可否が異なっていますが、各訓練にどのような効果があるのかは、長くなるのでここでは割愛させていただきます。",
      ],
    },
    {
      message: [
        "訓練を行うには、訓練したいキャラクターを選択後、実施する訓練メニューを選択してください。",
        "訓練予定の設定後、画面右下の訓練開始ボタンを押下するとその日の訓練が開始されます。",
        "訓練開始ボタンを押すまでは訓練予定を自由に組み替えることができます。",
      ],
    },
    {
      message: [
        "一度の訓練イベント中に訓練できる回数は画面左下の残り日数をご確認ください。",
        "日ごとに訓練を行うキャラクターを変えることができますので、好きなキャラクターに集中して訓練を行うか、バランスよく訓練を行うかはご自由にお選びください。",
      ],
    },
    {
      message: [
        "訓練についての説明は以上になります。",
        "有意義な訓練となることをお祈り申し上げます。",
      ],
    },
  ],
};
