import { WilTalkDefine } from ".";
import { WIL_IMAGE_ID } from "@/composables/games/wil/enums/image";
import { WIL_SOUND_ID } from "@/composables/games/wil/enums/sound";

export const WIL_TALK_DEFINES_CHPATER1: Array<WilTalkDefine> = [
  [
    {
      message: ["かつてこの世界には、魔物が蔓延っていた。"],
    },
    {
      message: [
        "魔物は魔王の力によって生み出され、魔王の意思によって人間を襲っていた。",
        "人々は魔王と魔物たちに怯えながら暮らしていた。",
      ],
    },
    {
      message: ["だがある日、聖剣を持った勇者が現れ、魔王を倒した。"],
    },
    {
      message: [
        "魔王の体は五体に分割して封印され、五つの国で管理されることとなった。",
        "右腕は焔(ほむら)の国、左腕は氷(こおり)の国、右足は嵐(あらし)の国、左足は金(こがね)の国、そして胴体と頭部は聖(ひじり)の国に、代々受け継がれてきた。",
      ],
    },
    {
      message: [
        "勇者は魔王が封印されている限り、魔物は減り、平和が続くだろうと語ったそうだ。",
        "実際、ここ数百年で魔物の目撃情報はほとんどない。",
      ],
    },
    {
      message: [
        "だが、世界の覇権を手にしようとしている焔の国が、魔王の力を利用するためにその封印の一部を解いてしまった。",
        "封印の一部が解かれたことにより、平和だった世界に再び魔物が現れ、各所で暴れだしているのであった。",
      ],
    },
    {
      talker: "村長",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      bgm: WIL_SOUND_ID.BGM_VILLAGE1,
      message: [
        "ヒカル、今年の収穫もよろしく頼むよ。",
        "若い男はヒカル一人だからね。頼りにしてるよ。",
      ],
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: ["はい。任せてください。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: ["(俺はヒカル。聖の国の端の田舎村に住む、ただの農民だ。)"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "村長",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: [
        "そうだ、最近妙なうめき声が聞こえるらしい。",
        "魔物なんて、私が子供のころには見なくなっていたが、一応気をつけてな。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: [
        "わかりました。",
        "でも、村に何かあったら、俺に任せてください。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "村長",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE,
      message: ["さすが、勇敢だ。", "頼りにしているよ。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      message: ["その日の夕方"],
    },
    {
      talker: "村の子供",
      sound: WIL_SOUND_ID.SE_MONSTER,
      bgm: WIL_SOUND_ID.BGM_PINCH1,
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["きゃー！"],
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SHADOW,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["あれは、魔物...？", "少なくとも人間ではないな...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SHADOW,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["...危ない！"],
      sound: WIL_SOUND_ID.SE_MONSTER,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SHADOW,
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [""],
      sound: WIL_SOUND_ID.SE_FIGHTING,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SHADOW,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["はぁはぁ...。", "もう大丈夫。早く逃げるんだ！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "村の子供",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["うん。ありがとう！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "(子供の手前、ああ言ったけど、かなり厳しいな...。このままじゃ村が...。)",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      sound: WIL_SOUND_ID.SE_MONSTER,
      message: ["...！？", "しまった！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO_SURPRISED,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SHADOW,
    },
    {
      talker: "？？？",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      sound: WIL_SOUND_ID.SE_GARD,
      message: [
        "おっと、危ない。",
        "よくここまで持ちこたえたな。",
        "もう大丈夫だ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "俺は聖騎士団の隊長、ザーグ！",
        "今からこの村は聖騎士団が守る！",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "聖騎士団！？",
        "帝都を守っているはずの聖騎士団がなんでこんなところに！？",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["そんなことより、君も早く逃げなさい。", "ここは危険だ！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["(逃げるか...？でも、この村は...。)"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "すみません、俺にも戦わせてください！",
        "足手まといにはならないようにします。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["この村を、守りたいんです！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "...いい目だ、気に入った！",
        "本来は許可できないが、俺は強いからな。何かあっても守ってやる。",
        "側から離れるなよ！",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["...はい！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      sound: WIL_SOUND_ID.SE_MONSTER,
      message: ["くるぞ！構えろ！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
  ],
  [
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      bgm: WIL_SOUND_ID.BGM_VILLAGE1,
      message: ["ふう、なんとか凌いだかな...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["それにしても君、やるなぁ。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["ありがとうございます。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "こんなことを頼むのもなんだが、聖騎士団に入ってみないか？",
        "君ほどの強さなら、歓迎するよ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "せっかくのお誘いですが、またいつこの村が襲われるか分からないので...。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "そうか、村を守るためか...。",
        "だが、それならなおさら聖騎士団に入った方がいい。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["それは、どういう...？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "実は、魔物が急に現れだしたのには理由があってね。",
        "最近、焔の国が魔王の封印の一部を解いてしまったようなんだ。",
        "漏れ出した魔王の魔力から、魔物が生まれ出しているらしい。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["そんなことが...。", "でも、どうして焔の国はそんなことを？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "魔王の力を利用して、他の国を支配し、世界の王になろうとしてるのさ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "おっと、少し喋りすぎてしまった。",
        "ま、とにかく焔の国を何とかしないと、この村どころか聖の国自体が危ないんだよ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["なるほど...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "さっきの戦いぶり、君の力には期待しているんだ。",
        "そうだ、村が心配なら駐屯兵を配置するように手配しておこう。",
        "徴兵でもない限りは常駐できるだろうし、今の君が守るよりは安全だろう。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["兵を配置していただけるんですか！？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["(ここまで言ってくれるんだ。あんまり気は乗らないけど...。)"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: ["分かりました。聖騎士団に入ります。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "よし！よく言ってくれた！",
        "じゃあ、いろいろと準備があるから、一週間後に帝都に来てくれ。",
        "楽しみにしているよ！",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_VILLAGE_EVENING,
      message: [
        "...行っちゃった。",
        "一週間後か...。",
        "少しでも役に立てるように、特訓しておくか。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
  ],
  [
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      bgm: WIL_SOUND_ID.BGM_HOLY_CASLE1,
      message: ["はあ、帝都は広いなあ。えーと、聖騎士団に会うには...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["おや、そこにいるのは、この間の少年じゃないか。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["あなたはあの時の...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: [
        "俺は聖騎士団隊長、ザーグ！...って前にも自己紹介したっけか？",
        "えーと、君は...",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["ヒカルです。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["ヒカル君、待っていたよ。", "じゃあ早速入団試験を始めようか。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["え、入団試験？", "そんなの聞いてないんですが...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: [
        "スカウトしたとはいえ、改めて力を確認しておきたいからね。",
        "なに、難しい試験じゃないさ。",
        "聖騎士団相手の三対三の模擬戦に勝ってくれれば良い。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: [
        "もちろん聖騎士団側は手加減するさ。",
        "君の味方二人は聖騎士団の中から見繕うから、好きに使ってくれ。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["試験って、人格とか知能の確認とかは？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: [
        "筆記試験とか倫理試験とかも考えたけど、面倒くさくてね。",
        "剣を交えれば大体わかるだろう。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["(この人、こんなに脳筋だったのか...。)"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["早速始めようか。", "彼らが君の味方だよ。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "騎士兵",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["よろしく。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
    },
    {
      talker: "魔導兵",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["よろしく。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["よろしくお願いします。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
    },
  ],
  [
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["はぁはぁ、なんとか勝てた...。"],
      bgm: WIL_SOUND_ID.BGM_HOLY_CASLE1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: [
        "まさか、本当に勝てるとは思ってなかったよ。",
        "やはり君は俺の期待に応えてくれそうだね。",
        "これからよろしく！",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["なんか、疲れた...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
    },
    {
      talker: "魔導兵",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: [
        "君、隊長にそそのかされて来たんでしょ？",
        "これから大変だよ...。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["え？"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
    },
    {
      talker: "騎士兵",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: [
        "もう分かってると思うけど、あの人勢いだけで動いてるところあるから...。",
        "まあ、一緒に頑張ろう。",
      ],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
    },
    {
      talker: "ヒカル",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["えぇ...。"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
    },
    {
      talker: "聖騎士団隊長 ザーグ",
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["さあ、さっそく特訓だ！"],
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
    },
  ],
];
