import { WilTalkDefine } from ".";
import { WIL_IMAGE_ID } from "@/composables/games/wil/enums/image";
import { WIL_SOUND_ID } from "@/composables/games/wil/enums/sound";

export const WIL_TALK_DEFINES_CHPATER5: Array<WilTalkDefine> = [
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      bgm: WIL_SOUND_ID.BGM_HOLY_CASLE1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["陛下、戻りました。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["ご苦労様。その顔を見るに、良い知らせはなさそうだね...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: [
        "はい。焔の国が攻めてきたところまでは推測通りだったのですが、敵の策にはまり、魔王の左腕を奪われてしまいました...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["それはまずいな...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["申し訳...ありません...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "今は悔いても仕方ない。次に考えるべきは、焔の国を落とすことと、魔王が復活した場合の備えについてだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["魔王が復活した場合の備えというと...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "もし魔王が復活してしまった場合、とれる対応は封印だけだ。しかし、かつて勇者が使用したと言われている封印魔法は光属性。つまり、私の知る限り、封印魔法を使える可能性があるのはヒカル君、君だけなんだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["それはつまり...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "そう、ヒカル君にはこれから封印魔法を覚えてもらう。猶予は一週間といったところかな。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["そんな...。魔王を倒すことはできないんですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "かつての勇者がなぜ魔王を倒さなかったのか。私も強すぎるが故かと思っていたのだが、どうもそうではなく、魔王はある特殊な力で倒さなければすぐに復活してしまうからだということが最近分かった。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["特殊な力...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "その力は天使の力と言われていたそうなんだが、天使なんて話に聞くのも初めてだからね。当てにできないんだよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["なるほど...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "でだ、ヒカル君が封印魔法を覚えるのに、レイナ君、ジョット君、君たちの力を貸してほしいんだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ジョット",
      message: ["やっと話に入れると思ったら、全然話が見えないんすが...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "恥ずかしながら、私は魔法はあまり得意ではなくてね。君たちからアドバイスしてあげてほしいんだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ジョット",
      message: ["まあ、そういうことなら協力しますけど。レイナは大丈夫か？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "レイナ",
      message: ["ええ。任せなさい。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "ヒカル",
      message: [
        "（レイナさん、まだ元気ないな...。お父さんが亡くなったんだし、無理もないか...。）",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "さっき言った通り、猶予は一週間とする。もしそれより早く魔王が復活すればどちらにせよ我々にはどうすることもできない。一週間を超えてもヒカル君が封印魔法を覚えられなかった場合は...",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["任せてください。絶対に習得して見せます。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["ああ。頼りにしてるよ。"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["ヒカル君、約束の一週間がたったが、調子はどうだろうか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ジョット",
      message: ["今必死にやってるところだから、邪魔しないでやってださい。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["これは失礼した。で、ジョット君から見てどうなんだ？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ジョット",
      message: [
        "はっきり言って、よくわかんないっすね。対象とする敵がいないし、発動した後どうなるのかも想像できないんで。ただ、ヒカルはもう少しで掴めそうって言ってましたよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "魔導兵",
      message: [
        "古文書には光で相手を包み込むイメージだと書いていましたが、包み込むってかなり難しいんすよ。魔法は体内の魔素を放出して使うものなんで、放出した魔素の動きを殺さないといけないんすが、魔法としての形を保ったまま動きを止めるとなると、俺にはやり方が分からない。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "な、なんだかよくわからないが、難しいということはわかったよ。しかし、期限は今日までだ...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: [
        "（魔法で相手を包み込むには魔素の動きをできるだけ殺さないといけない。放出した魔素の動きを止めるなんてこと..。）",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: [
        "そうか、逆向きに力を与えれば動きは止められる！つまり、二つの魔法がぶつかるように放出すればいいのか！あとはぶつかった後に球形になるように調整して...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      sound: WIL_SOUND_ID.SE_HOLY2,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["おお！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: ["まじか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["よくわからんけど、上手くいったのか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: [
        "はい！これなら光の魔法で敵を包み、闇の力を封じることができます！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "レイナ",
      message: ["さすがね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "よし、これで勝機が見えた！この一週間焔の国が攻めてこなかったのを見るに、魔王の復活には手間取っているようだ。今のうちに攻め切ってしまおう！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["はい！"],
    },
    { background: WIL_IMAGE_ID.BACKGROUND_BLACK, message: [""] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      bgm: WIL_SOUND_ID.BGM_FIRE_LAND1,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "サジン",
      message: ["殿、敵が攻め込んできました。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      bgm: WIL_SOUND_ID.BGM_FIRE_LAND1,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["やっと来たか。遅ぇんだよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      bgm: WIL_SOUND_ID.BGM_FIRE_LAND1,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: ["しかしグレン殿ぉ、魔王はまだ復活してませんよぉ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["うるせえ。あいつらをつぶすのに俺たち以外の力はいらねえ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: [
        "話が違うではありませんかぁ。我々の力を貸す代わりに、魔王復活のお手伝いをしてくれるという約束だったはずではぁ？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: [
        "俺はてめえらが最強の敵を用意するっていうから乗っただけだ。目の前に敵がいるのに、それ以外に目をくれる馬鹿がいるか？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: [
        "馬鹿ってこれはまたぁ...。僕は人工兵を開発した世紀の大天才ですよぉ？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "サジン",
      message: ["ホックス殿、なぜ魔王はまだ復活しないのですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "ホックス",
      message: [
        "よくぞ聞いてくれました、サジン殿ぉ！実は魔王が復活するためには大量の魔素が必要なのですが、それが全然足りないのです！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "サジン",
      message: ["して、魔素はどのように供給されるので？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "ホックス",
      message: [
        "我々が地道に送り込んでも良いのですがぁ、高い魔力を持った人間を贄とするのが一番早いですねぇ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "サジン",
      message: [
        "なるほど。であれば敵兵を倒していけば自然と魔王復活も近づくと。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "ホックス",
      message: ["さすがサジン殿ぉ！理解が早い！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "サジン",
      message: [
        "殿、殿のお望み通り、まずは目の前の敵を片付けましょう。敵兵を倒すほど、殿の望む最強の敵、魔王の復活も近づきまする。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["っは！そんな下らねえこと話してる間に来たぞ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ヒカル",
      message: ["お前が焔の国の大将か！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["そうだ。一番強えのはてめえか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ヒカル",
      message: ["強さは関係ない。平和のために、あなたには大人しくしてもらう！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["っは！せいぜい楽しませろ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "サジン",
      message: ["センプウ、我々も。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WIND_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "センプウ",
      message: ["御意。"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      bgm: WIL_SOUND_ID.BGM_FIRE_LAND1,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["やるじゃねえか。面白くなってきたなあ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      sound: WIL_SOUND_ID.SE_GARD,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: ["あれぇ？完全に油断してると思ったんですがぁ？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["てめえ、何しやがる。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["なんだ？仲間割れか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: [
        "言ったでしょぉ？魔王の復活には高い魔力を持った人間が必要だって。だから、魔王復活のために死んでくださいよぉ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      sound: WIL_SOUND_ID.SE_SLASH,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: ["うっ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["雑魚が。てめえがこの俺に勝てるわけねえだろうが。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["邪魔が入ったな。さあ、続きをやろうぜ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: ["っく。くはっ！くはははははははっ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["あぁ？なに笑ってやがる。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: [
        "感謝しますよぉ、グレン殿ぉ。これで魔王が復活する。しかも、その力はすべて僕の物になる！！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["ど、どういこと？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      talker: "ホックス",
      message: [
        "魔王復活のために必要な魔力は僕の分で十分。そして、この世紀の大天才によって、最後に贄になった人間が魔王の力を得られるように制御ずみぃ！つまり今から...",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      bgm: WIL_SOUND_ID.BGM_PINCH3,
      sound: WIL_SOUND_ID.SE_MONSTER,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ホックス",
      message: ["僕が魔王だ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "レイナ",
      message: ["禍々しい力を感じるわ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ジョット",
      message: ["あいつ、魔王の力を吸収したのか...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ヒカル",
      message: ["これが、魔王...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ホックス",
      message: ["魔王の復活ついでに、もう一つ絶望を見せてあげよう。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_THUNDER_SOLDIER,
      talker: "闇ザーグ",
      message: ["俺は...聖騎士団隊長...ザーグ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_THUNDER_SOLDIER,
      talker: "ヒカル",
      message: ["ザ、ザーグさん！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ホックス",
      message: ["そう。君の尊敬するザーグさん。でも、もう魔物。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ヒカル",
      message: ["そんな...。なんで...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ホックス",
      message: [
        "あれぇ、知らなかったぁ？魔王の魔力には非生物を魔物化させる力があるんだよぉ？",
        "死人だって非生物だからねぇ、魔物化できちゃうんだよぉ。",
        "ついでにもう一人。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_WATER_SOLDIER,
      talker: "闇スイゲツ",
      message: ["..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_WATER_SOLDIER,
      talker: "シノブ",
      message: ["スイゲツ！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_WATER_SOLDIER,
      talker: "グレン",
      message: ["帰ってこないと思ったらくたばってやがったか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ホックス",
      message: [
        "君たちもすぐに仲間入りさせてあげるよぉ。",
        "これで世界は僕のもの。",
        "さあ、全員ひざまずけ！",
      ],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["皆さん、あれを使います！少し時間稼ぎお願いします！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "レイナ",
      message: ["任せなさい！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      message: ["こっちだ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      message: ["っはは！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["（...今だ！）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "システム",
      message: ["ヒカルは封印聖域を発動した。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ホックス",
      message: ["ぐわぁぁぁああああああ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ジョット",
      message: ["やったか！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ホックス",
      message: [
        "なーんちゃって。かつて魔王がやられた魔法を対策してないわけないでしょぉ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ホックス",
      message: ["新しい魔王に、その封印魔法は効きませーん！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ヒカル",
      message: ["そん...な...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SATAN,
      talker: "ホックス",
      message: ["君たちの相手をしたおかげで、大分魔王の力が馴染んできたよぉ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      sound: WIL_SOUND_ID.SE_MONSTER,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ホックス",
      message: ["これで終わりにしよう。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      sound: WIL_SOUND_ID.SE_BLOW3,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵&魔導兵",
      message: ["ぐへぇ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      sound: WIL_SOUND_ID.SE_FIRE2,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      message: ["くそっ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      sound: WIL_SOUND_ID.SE_DARK1,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "シノブ&レイナ",
      message: ["っう！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["みんな！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ホックス",
      message: ["ああ、この圧倒的な強さ。ああ、この絶望感。まさに魔王！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ヒカル",
      message: ["そんな...ここで...終わり？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_THUNDER_SOLDIER,
      talker: "闇ザーグ",
      message: ["ヒカル...信じてる...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_THUNDER_SOLDIER,
      talker: "ヒカル",
      message: ["ザーグさん...。でも、魔王を倒すには天使の力が必要で...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_THUNDER_SOLDIER,
      talker: "闇ザーグ",
      message: ["俺は...お前を...信じてる...！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ホックス",
      message: [
        "魔物が自我を持つなんて！人間を母体にした影響かなぁ？実に面白い！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ヒカル",
      message: [
        "...そうだ。ない力なら創り出す。それが、俺にできる最後の足掻き！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ホックス",
      message: ["なにそれぇ？今から新しい魔法なんて、使えるわけないでしょぉ？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ヒカル",
      message: ["いいや、俺ならできる！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ヒカル",
      message: ["（天使の力を...魔王を倒す力を...創造する！）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      sound: WIL_SOUND_ID.SE_HOLY2,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["なんだか暖かいです...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "レイナ",
      message: ["力が...みなぎってくるわ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["これならまた戦える！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ホックス",
      message: [
        "何が起こったか知らないけどぉ、何度立ち上がろうが同じことぉ！さらなる絶望を与えるだけさぁ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["おい、小僧。念願の最強の敵だ。俺も混ぜろ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ヒカル",
      message: ["グレン...。ありがとう。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["礼はいらねえ。終わったらもう一回戦いやがれ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,

      talker: "ヒカル",
      message: ["（それは嫌だ...。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ヒカル",
      message: ["よし、みんな、行こう！"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_DARK_MONSTER_SUPER_SATAN,
      talker: "ホックス",
      message: ["そんな...魔王の力が...ありえないぃ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      talker: "ヒカル",
      message: ["はぁ...はぁ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["消えた...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "レイナ",
      message: ["倒したの...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_SUPER_HERO,
      talker: "ヒカル",
      message: ["やっ...た...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_FIRE_LAND_SHODDY_CATSLE,
      sound: WIL_SOUND_ID.SE_FALL_DOWN,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_FIRE_LAND_SHODDY_CATSLE,
      left: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      message: ["ヒカル！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["うぅ...ここは...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["起きましたか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "ヒカル",
      message: ["シノブちゃん？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["起きるのが遅いですよ。世界は...大変なことになってます。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "ヒカル",
      message: ["え！？大変ってまさか...！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "レイナ",
      message: ["ヒカル！起きたのね！良かった...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["随分と寝坊癖があったんだな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: ["みんな...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "やっと起きたんだね、ヒカル君。いや、今は世界を救った英雄か勇者様とでも呼ぶべきかな。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["それじゃあ世界は...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["君のおかげで、救われたよ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: [
        "良かった...。じゃあ大変なことになっているっていうのは嘘か...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "いや、大変なことにはなってるかな...。この戦いで各国の王がいなくなったわけだからね。でも...",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "レイナ",
      message: [
        "あなたが寝てる間に、私は王の座につかせてもらったわ。フロリア家に、お父様に恥じないように仕切っていくわ。だから、これからはちゃんと敬いなさいよね。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "ヒカル",
      message: ["ええ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["俺も正式に嵐の国の王になった。舐めた口きいたら処す！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "ヒカル",
      message: ["二人とも、王様になったんですね...。あれ、グレンは？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "ジョット",
      message: [
        "あいつはあの後、すぐに姿を消したよ。こっちもボロボロだし、深追いはできなかったんだよな。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "焔の国と金の国は長を失ったから、三国同盟で管理することになった。人も土地もほとんど倍を見ないといけなくなったから、これが大変でね。二人と今協力してなんとかって感じだよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "だが、魔物は徐々に減りつつある。あと数年もすればついこの間までと同じ、平和な世界に戻ると思うよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["そうなんですね...。良かった...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "レイナ",
      message: ["ヒカル、あなたはこれからどうするの？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "ヒカル",
      message: [
        "俺は...俺は村に戻ろうかと思います。もとはと言えば村の平和のために聖騎士団に入ったので、平和になった今、俺が聖騎士団にいる意味はなくなったので。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["ええ！？それは困るよ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["え？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "さっきも言ったけど、減ってるとはいえ、魔物はまだ残ってるんだ！完全にいなくなるまでは聖騎士団として闘ってほしいんだが...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["えーと...俺じゃないとだめですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["世界を救った英雄様にお願いしたいんだ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["安心してください。私も手伝います。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICE_GARDIAN_QUEEN,
      talker: "レイナ",
      message: [
        "氷の国周りもお願いするわ。",
        "つ、ついでに、顔を見せに来なさい！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["お、じゃあ嵐の国方も頼むな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["そんな...。", "俺の生活には平和は来ないんですか...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      message: [
        "こうして、世界は一人の聖騎士の力によって、平和へと導かれたのであった。",
      ],
    },
  ],
];
