import { WilTalkDefine } from ".";
import { WIL_IMAGE_ID } from "@/composables/games/wil/enums/image";
import { WIL_SOUND_ID } from "@/composables/games/wil/enums/sound";

export const WIL_TALK_DEFINES_CHPATER3: Array<WilTalkDefine> = [
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      bgm: WIL_SOUND_ID.BGM_ICE_LAND1,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "しかし、あの魔人を追い払ったのはいいものの、みんなかなり傷ついてしまったな...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "すぐにでも帰りたいところだけど、この状態で帰るのはむしろ危なそうだね。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "フロリア王、すまないが皆が回復するまで数日ほど滞在させていただけないだろうか？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "フロリア王",
      message: ["もちろんじゃ。ゆっくり休んでいくといい。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "皇帝",
      message: [
        "助かるよ。ザーグ、皆が回復するまでにどれくらいかかりそうかな？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["二、三日ほどでしょうか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["分かった。では出発は三日後としようか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["承知いたしました。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "フロリア王よ、その間、今後の作戦について話させていただきたい。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "フロリア王",
      message: ["あいわかった。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "ということで、三日間療養ということになったんだが、お前らは元気だよな？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "騎士兵&魔導兵",
      message: ["え？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["実は魔人との戦いで大怪我をしていて...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["どこに傷があるんだ？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "魔導兵",
      message: ["実は魔人との戦いで膝に矢を受けてしまって...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["あの魔人、矢なんて使ってなかっただろ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "レイナ様に頼んで訓練に混ぜてもらえることになったから、お前らは参加するように。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "騎士兵&魔導兵",
      message: ["...はい。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["ヒカルも来れるか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["もちろんです！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: [
        "（あの氷の魔人に、俺はほとんどダメージを与えられなかった...。もっと強くならないと！）",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ザーグ",
      message: ["レイナ様、よろしくお願いします。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["せっかく参加するんだから、厳しくいかないとね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "補助兵",
      message: ["老体には堪えるのぉ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["あなた、まだ20代じゃなかったかしら？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "守護兵",
      message: ["レイナ様、怖い。訓練、やだ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["何か言ったかしら？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BATTLE_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["（氷の国の人たちも仲いいなあ。）"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      bgm: WIL_SOUND_ID.BGM_ICE_LAND1,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["そろそろ発てるかな？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["はい。準備はできています。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "それじゃあ出発...の前に、今後の方針について先に話しておかないとね。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["今後の方針...と言いますと？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "実は、みんなが休んでいる間にフロリア王様と話してね。金の国、嵐の国とも早急に同盟を結ぶべきだという結論に至ったんだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "で、まずは比較的外交的な嵐の国に話をつけに行くことになったんだ。今から。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["今からですか！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "みんなには負担かけて申し訳ないけど、状況も状況だからできるだけ急ぎたいんだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["陛下の命とあれば従いますが...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "本当にすまないね。とはいえ、嵐の国はここから聖の国を挟んで反対側。一度国を経由してから向かおうかと思ってる。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["なるほど...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "あと、これは三国同盟になるから、氷の国からも使者を出してもらうことになった。まあつまり、氷の国の一軍も一緒に行動することになるから、仲良くするように。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["おいおい、盛りだくさんだなぁ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["氷の国の使者ってもしかして...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["そういうことで、よろしくね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["やっぱり...。"],
    },
    { background: WIL_IMAGE_ID.BACKGROUND_BLACK, message: [""] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      bgm: WIL_SOUND_ID.BGM_HOLY_CASLE1,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["いやぁ、帰りは何事もなく、良かった！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: [
        "何事もなかったというか、ほとんどの魔物をザーグさんとレイナさんで倒してたからでは...？。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["ヒカルも大概だったけどな。というか、レイナ様強すぎない？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "守護兵",
      message: ["レイナ様、怖い。怒らす、ダメ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "慣れた土地なんだから、これくらい当然でしょ！というか、あなたたちももっと戦いなさいよ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "補助兵",
      message: ["怒るとシワが増えるよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["うるさいわね！20代のくせに姑みたいなこと言わないでよ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["まあまあ、あんまり怒るともったいないですよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["何がもったいないのよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: [
        "だって、レイナさん美人じゃないですか。笑ってた方が良いですよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "よ、余計なお世話よ！王族なんだから、び、美人に決まってるでしょ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "補助兵",
      message: ["照れてる。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["もう、うるさい！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["えーと、話してもいいかな？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["失礼しました！お前ら、陛下の前だぞ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["すみません...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "これから国に残っていた兵士で荷物の積み込みとかをやってもらうから、みんなは一旦休んでくれ。出発は明日の早朝ということで。氷の国の皆さんには宿をとってあるので、そこで休んでください。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["承知しました。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "レイナ",
      message: ["分かりました。ありがとうございます。"],
    },
    { background: WIL_IMAGE_ID.BACKGROUND_BLACK, message: [""] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      message: ["翌日"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["みんな、揃ってるかな？それじゃあ..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "側近",
      message: ["陛下、至急お知らせしたいことが！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["どうした？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "側近",
      message: [
        "実は...。嵐の国が焔の国から攻撃を受けているという知らせが入りまして...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["何！？それは本当か！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "側近",
      message: [
        "嵐の国は奮闘しているようですが、押し切られるのも時間の問題のようで...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["そうか...それはまずいな...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["急いで救援に向かいましょう！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["そうだな。急いで向かい、救援しなければ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "側近",
      message: ["なりません。皇帝陛下自ら、それも他国の戦地に赴くなど。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["そうか。となると...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["俺も残らないといけないですね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["ザーグさんも！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "俺たち聖騎士団は聖の国と皇帝陛下を守るための組織だ。隊長である俺が陛下のもとを離れるわけにはいかない。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "レイナ様、他国の王女様にこんなことを頼むのは忍びないのですが、聖騎士団の隊員を率いて嵐の国を助けに行っていただけないでしょうか？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "レイナ",
      message: ["いいわ。氷の国と聖の国の連合軍は一時的に私が指揮します。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["（ザーグさん、いないのか。ちょっと不安だな...。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["ヒカル、聖騎士団のことは頼んだぞ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["え、俺ですか！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "お前を一番信頼しているんだ。会ってから日も浅いのに、なんでだろうな。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ヒカル",
      message: ["...分かりました。任せてください。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["それじゃあ連合軍、嵐の国に急いで向かうわよ！"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["もうすぐ嵐の国よ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["嵐の国、無事でしょうか...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "嵐の国は丈夫な塀があって防御には長けてるし、あそこの王族もかなりの手練れだわ。そう簡単にはやられてないと思うけど...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["話をしてるうちに、嵐の国の塀が見えてきたわ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["あれ、魔物に襲われてませんか！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "どういうこと！？嵐の国は焔の国に攻められてるって話だったはずだわ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["とにかく、魔物を倒しましょう！"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["大体片付いたかしら。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["さすがに、あの魔人に比べると楽勝でしたね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "？？？",
      message: ["お前ら、何者だ！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: [
        "私はフロリア王女、レイナよ！嵐の国が焔の国に攻められてると聞いて救援に来たの！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "？？？",
      message: ["なんだ、レイナか。久しぶりだな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: ["あら、ジョットじゃない。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["えーとこの人は...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["彼は嵐の国の王様の弟、ジョットよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["...今は代理の王ってところだがな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: ["...！？ということはお兄様は...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "死んだよ。焔の国のやつらとの戦いでな。まあ詳しい話は城で話すよ。",
      ],
    },
    { background: WIL_IMAGE_ID.BACKGROUND_BLACK, message: [""] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: ["それで、嵐の国は今どうなってるの？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["その前に、そいつ誰だ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: ["俺は聖騎士団のヒカルです。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: ["一応、聖の国の使者よ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: ["隊長が皇帝の護衛で来れないので、代わりに。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["なるほどね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: [
        "あの、なんで魔物に襲われていたんですか？我々は焔の国に攻められてると聞いて救援に来たのですが...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "なんでだろうな。焔の国も来たんだよ。で、追い返した。でも、一息ついてたところに魔物が襲ってきたんだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "普段なら大したことない魔物だったんだが、疲弊しきった軍にはそれでも十分すぎた。兄貴はその時に...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: ["そう...。それは大変だったわね...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "気になるのは魔物たちがタイミングを見計らったかのように攻めてきたことだ。偶然にしては最悪のタイミングすぎる。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: [
        "もしかしたら、焔の国が魔物を使役できるほど魔王の力を使いこなしてるのかもしれないわね。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["それと、もう一つ気になったのが..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_OUTSIDE,
      sound: WIL_SOUND_ID.SE_EXPLOSION,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["また襲撃か！話は後だ。迎え撃つ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["俺たちも行きましょう！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["もちろんよ！"],
    },
    { background: WIL_IMAGE_ID.BACKGROUND_BLACK, message: [""] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTER_ARCHER,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "火弓兵",
      message: [
        "ジョット様！お待ちしておりました。我々だけではかなり苦しく....。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTER_ARCHER,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["ご苦労。よく持ちこたえてくれた。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      sound: WIL_SOUND_ID.SE_MONSTER,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["何よ、あれ？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["魔物？それにしては生気がないような...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "あれはたぶん金の国の作った兵器だ。さっき言いかけたもう一つの気になる点だが、おそらく焔の国と金の国は手を組んでる。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: ["そんな！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: [
        "...ありえない話じゃないわね。金の国は何を考えてるか分からないもの。金の国に利益のある条件なら手を組みかねないわ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["ジョットさん、危ない！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      sound: WIL_SOUND_ID.SE_GARD,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "？？？",
      message: ["おや、あと少しだったのですが...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "ジョット",
      message: ["お、お前、どこから！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "？？？",
      message: [
        "そんなことより、あなたを倒せば任務完了です。さっさと倒されてください。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "レイナ",
      message: [
        "奇襲に失敗したのは痛かったわね。この数相手に、一人じゃ何もできないわよ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "？？？",
      message: ["そうですね。でも、こちらも一人ではないので。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      talker: "人工兵",
      message: ["センメツシマス。センメツシマス。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      talker: "ヒカル",
      message: ["いつの間に！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "？？？",
      message: ["強いて言うなら、私に気を取られている間でしょうか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "ジョット",
      message: ["お前、何者だ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "？？？",
      message: ["わざわざ敵に素性を明かすわけないでしょう？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "人工兵",
      message: ["ホムラノクニシノビグン、ダイニタイチョウ、ゴメイレイヲ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["...なんで言っちゃうんですか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "レイナ",
      message: ["忍軍。焔の国の特殊部隊ね。名を名乗りなさい！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: [
        "忍は無駄に情報を話さないものです。名前など、明かすわけないでしょう。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "人工兵",
      message: ["シキカン、シノブ、ゴメイレイヲ！！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "レイナ",
      message: ["..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "ジョット",
      message: ["..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "ヒカル",
      message: ["..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["...ポンコツ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "ヒカル",
      message: ["（この子、ちょっと憎めないな...。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["もういいです。全員消せば関係ないですから。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "ジョット",
      message: ["来るぞ！"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.SKILL_THUNDER_HORIZONTAL,
      talker: "シノブ",
      message: ["っく、ポンコツだけでは無理でしたか...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "ジョット",
      message: ["諦めるんだな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["ちょっと、もしかして殺すんですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ジョット",
      message: ["敵の刺客だからな。仕方ないだろ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: [
        "だめですよ！この子、まだ小さな女の子じゃないですか！しかも、なんかちょっと憎めないし...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ジョット",
      message: [
        "じゃあどうするんだよ。このまま逃がすわけにはいかないし、捕虜にして生かしておくほどの余裕は今のこの国にはないぞ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: ["それは..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["情けはいりませんよ。どうせ、国に帰ればただではすみませんし。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "？？？",
      message: ["シノブちゃん、時間稼ぎおつかれさーん。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "ジョット",
      message: ["誰だ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "？？？",
      message: [
        "俺はスイゲツ。焔の国の侍さ。あんたらがシノブちゃんを相手にしている間に入らせてもらったよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "ヒカル",
      message: ["あれ、あなたは名乗るんですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "スイゲツ",
      message: [
        "シノブちゃんは言わば諜報部員。秘密を守りながら情報を集めるのが仕事。俺は単純な戦闘兵。だから名前くらいどうってことないさ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "レイナ",
      message: ["戦闘兵ってことは、かなり強そうね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "ジョット",
      message: ["でも相手は一人だ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      talker: "科学兵",
      message: ["スイゲツさん、速いですよぉ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      talker: "ジョット",
      message: ["増援！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "スイゲツ",
      message: ["あれ？置いてきちゃってた？ごめんごめん。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "科学兵",
      message: [
        "もしかして戦闘ですかい？あっしらは戦えないんで守ってくださいよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      talker: "レイナ",
      message: ["戦力にはならなさそうね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "スイゲツ",
      message: [
        "さすがにこの人数相手じゃ命の保証はできないねえ。生きたかったら自分で何とかしなよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "科学兵",
      message: ["ええ...。仕方ないっすねえ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      sound: WIL_SOUND_ID.SE_WARP,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      talker: "ヒカル",
      message: ["何もないところから兵が！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      talker: "レイナ",
      message: ["召喚する魔法！？聞いたことないわ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      sound: WIL_SOUND_ID.SE_WARP,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      right: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_ANDROID,
      talker: "科学兵",
      message: ["とりあえず、これだけいればいいでしょう。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "スイゲツ",
      message: ["準備はできたかい？じゃあ、サクっと終わらせますか。"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "スイゲツ",
      message: ["やるねえ。ここはいったん引くとしますか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_MEMBER,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "科学兵",
      message: ["スイゲツさん、仕込みはばっちりですぜ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "スイゲツ",
      message: ["そう。じゃあシノブちゃん、悪いけど俺たちのために死んでくれ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "シノブ",
      message: ["...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_WATER_SOLDIER,
      talker: "レイナ",
      message: ["待ちなさい！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      sound: WIL_SOUND_ID.SE_EXPLOSION,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["うぅ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["シノブちゃん！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "なんてやつらだ。自分たちが生き残るために味方に爆弾を仕込んでやがった...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["とにかく手当を！"],
    },
    { background: WIL_IMAGE_ID.BACKGROUND_BLACK, message: [""] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["とりあえず、一命はとりとめたわ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "で、あいつどうするんだ？さっきも言ったけど、うちではどうにもできないぞ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: ["...嵐の国で生かしておけないなら俺が引き取ります。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["なんでそこまで執着するんだ？敵兵だぞ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: [
        "人間同士の争いで死人が出るなんて絶対に間違ってる。救える命があるなら救いたいんです。それに、この子はまだ小さいし、今からでも生き方を変えられると思うんです。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["...俺は知らねえぞ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "まあ今更殺す気にはなれないわね。ザーグには私からも話をつけてあげるわ。今はそれより...",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: ["ジョット、氷の国、聖の国と同盟を組んでくれない？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "よくこの状況で切り出したな...。まあ今の俺たちに貢献できることはないが、それでもいいなら喜んで受け入れるよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: ["もちろんいいわ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["え、勝手に決めちゃっていいんですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "レイナ",
      message: ["お父様なら許してくださるわ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["まあ陛下も許してくれそうですけど...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "レイナ",
      message: ["何かあっても私が責任を持つわ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["俺はありがたいが、それでいいのか...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: ["それだけ猶予がないのよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "そんな中で済まないんだが、またいつあいつらが攻めてくるかわからない。せめて塀の修復が終わるまで兵を貸してくれないか？一週間、いや五日でいい。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "レイナ",
      message: [
        "同盟を組んですぐ壊滅しましたじゃ意味ないものね。分かったわ。報告用に何人か返して、私たちは残りましょう。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["え、俺もですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "レイナ",
      message: [
        "し、仕方ないじゃない。あいつらがまた来たら、あなたくらいの戦力は必要になるのよ！それに、この子はまだ動ける状態じゃないわ！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "レイナ",
      message: [
        "だ、だからあなたは私のそばに...じゃなくて、私たちと一緒に嵐の国を守りなさい！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["わ、分かりました...。（すごい気迫だ...。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["悪いな。助かるよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "レイナ",
      message: [
        "じゃあ私たちも復興作業を手伝いましょうか。もちろん、訓練もするわよ。",
      ],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["おかげでだいぶ片付いたよ。ありがとう。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ヒカル",
      message: ["結局、あれから焔の国は攻めてきませんでしたね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: [
        "まあ、それなりに戦力は削ったからな。向こうも慎重になったんだろ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "とりあえずもう大丈夫そうね。あの子もだいぶ回復したみたいだし、そろそろ帰りましょうか。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      talker: "シノブ",
      message: ["..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      right: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
      talker: "ジョット",
      message: ["みんな、本当に助かったよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["結構長い出征になっちゃいましたね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: ["そうね。早く帰らないと、自国が心配だわ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      message: ["一方そのころ、焔の国にて"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "？？？",
      message: ["殿、スイゲツが敗走してきました。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "焔の国の殿",
      message: ["ちっ！雑魚が！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "？？？",
      message: ["グレン殿ぉ、機嫌悪いですねぇ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["おいクソ野郎、勝手に入ってくるんじゃねぇ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "？？？",
      message: ["ホックス殿、お控えください。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "ホックス",
      message: [
        "グレン殿もサジン殿も冷たいなぁ。同盟なんだから、ちょっとくらいいいじゃないかぁ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: ["斬られてぇのか？さっさと出てけ！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: ["まぁまぁ。私も用なく来てるわけじゃないんですよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_SAND_SPY,
      talker: "サジン",
      message: ["いかがなさったのでしょうか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: ["こっちの作戦、上手くいったよ。まあ二体もやられちゃったけど。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "グレン",
      message: [
        "余計なことしやがって。あそこの隊長、強いんだろ？俺がやりたかったんだがなぁ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
      left: WIL_IMAGE_ID.CHARACTER_SMOG_LABORATORY_DOCTOR,
      right: WIL_IMAGE_ID.CHARACTER_INFERUNITY_SAMURAIS_KING,
      talker: "ホックス",
      message: ["まあ、今となっては『強かった』ですけどねぇ。"],
    },
    { background: WIL_IMAGE_ID.BACKGROUND_BLACK, message: [""] },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["どうなってるんだ、これ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "シノブ",
      message: ["これがあなたの国ですか？随分ボロボロですが。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "レイナ",
      message: ["とりあえず、人を探しましょう！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["数分後"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["陛下！ご無事でしょうか！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["ヒカル君！良かった、無事に帰ってきたんだね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["一体、何があったんですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["魔人が来たんだ。それも、三体。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["魔人！？...ザーグさんは！？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["ザーグ君は...私を守って...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["そんな、まさか...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "彼は素晴らしい隊長だったよ...。ザーグ君のおかげで、私も、この国も守られた。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["ザーグさん...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "レイナ",
      message: [
        "こんな時にごめんなさい、私もお父様が心配だわ。急いで帰らせてもらうわ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      talker: "ヒカル",
      message: ["はい...。お気をつけて...。（ザーグさん...。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      message: ["翌日"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      talker: "神父",
      message: ["故人、ザーグは、聖騎士団隊長として見事に職務を全うし..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["（まだ信じられない...。あのザーグさんが...。）"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["うわぁぁぁぁああ！ザーグさんんん！！！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: ["あんまり泣くなよ。ザーグさんに怒られるぞ...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["聖騎士団のみんな、話がある。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "ザーグ君は立派な聖騎士としてその職務を全うした。しかし、争いはまだ終わっていない。再び平和な世界を取り戻すために、新しい隊長を決める必要がある。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "ヒカル君、君が聖騎士団の隊長となって、焔の国の殿を討ち、魔物のいない世界を作り出してほしい。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["俺が隊長ですか？でも、俺はまだ新米で..."],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "ザーグ君は君を信頼していると言っていた。それに私も不思議と君を頼りたい気持ちになる。君なら、なんとかしてくれるんじゃないかと。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ヒカル",
      message: ["そんな...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "君は確か光属性の魔法を使うね。この国はかつて魔王を封印した勇者様によって作られた国で、その勇者様も光属性の魔法を使ったらしい。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "もしかしたら、君の持っている光属性の魔力が、無意識のうちに我々の希望となっているのかもしれない。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["俺も、ヒカルが隊長なら安心できるよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: ["他の奴よりはましだな。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_OUTSIDE,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["分かりました。ザーグさんの意思は俺が継ぎます。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      left: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["こうして俺は、聖騎士団の隊長となった。"],
    },
  ],
];
