import { WilTalkDefine } from "@/composables/games/wil/defines/talks/index";
import { WIL_IMAGE_ID } from "@/composables/games/wil/enums/image";
import { WIL_SOUND_ID } from "@/composables/games/wil/enums/sound";

export const WIL_SUB_TALK_DEFINES_HOLY_KNIGHTS_LEADER: Array<WilTalkDefine> = [
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["隊長の仕事"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      bgm: WIL_SOUND_ID.BGM_VILLAGE1,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "今日の訓練はここまで！",
        "俺は隊長業務があるから、後片付けよろしく！",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["あー疲れた。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      talker: "魔導兵",
      message: ["もう動けん。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: [
        "ザーグさん、隊長業務って言ってましたけど、何やってるんでしょうか？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "騎士兵",
      message: [
        "あーあれね。隊長になると、俺たちみたいな下の人間だけじゃなくて、上と話したりするらしいよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["上っていうと...？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "騎士兵",
      message: [
        "主に皇帝陛下だな。陛下の外出予定を聞いて護衛の準備をしたりとか、聖騎士団の予算の調整したりとか色々話してるみたいだ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "ヒカル",
      message: ["そんなこともやるんですね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HERO,
      talker: "騎士兵",
      message: ["ああ見えて意外と頭脳労働もしてるんだよなぁ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      bgm: WIL_SOUND_ID.BGM_HOLY_CASLE1,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: [
        "陛下！来年度の聖騎士団の予算ですが、今年度と同じでよいですか！？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "えーと、聖騎士団には頑張ってもらってるし、焔の国との決戦もあるだろうから、予算は増やしたほうが良いんじゃないかな？",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: [
        "なるほど！じゃあ増やしましょう！それと、陛下の外出予定ですが...",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: [
        "まとめておいたから護衛よろしくね。",
        "あと、この日は氷の国までの遠出になるから、いつもより多めに人を割いてもらえると助かるよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "ザーグ",
      message: ["わかりました！できるだけ人員を割くようにします！"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_CASTLE,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_LAND_EMPEROR,
      talker: "皇帝",
      message: ["...分かってると思うけど、国を守るための人は残しておいてね。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      message: ["皇帝陛下が有能だった。"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["ザーグと騎士兵"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      bgm: WIL_SOUND_ID.BGM_VILLAGE1,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["おい、ちょっと手伝ってくれないか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["何ですか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["新技を思いついてね。試しに受けてみてほしいんだ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["げ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["なーに手加減はするよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["ほんとですかぁ？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["部下を痛めつけるようなことするわけないじゃないか。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["...ちょっとだけですよ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      sound: WIL_SOUND_ID.SE_EXPLOSION,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      message: [""],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER_WOUNDED,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["...手加減の意味知ってますか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER_WOUNDED,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "悪い悪い！",
        "ちょっと気合が入りすぎてしまった！まあ、いい練習になったよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER_WOUNDED,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["次はこの技なんだけど...。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_TRAINING_ROOM,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER_WOUNDED,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["もう勘弁してください。"],
    },
  ],
  [
    {
      background: WIL_IMAGE_ID.BACKGROUND_BLACK,
      talker: "サブイベント",
      message: ["気の合う人たち"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      bgm: WIL_SOUND_ID.BGM_VILLAGE1,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER_WOUNDED,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["はっはっは。お前ら、しごかれてるなぁ。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER_WOUNDED,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: [
        "笑い事じゃないですよ。あの魔人と戦った後でこんなきつい訓練やったら死んじゃいますって...。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER_WOUNDED,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["おいおい、他人様の国で弱音吐くなんて、聖騎士失格だぞ～。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN_WOUNDED,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "魔導兵",
      message: ["失格でもいい。おうちに帰りたい。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "レイナ",
      message: ["あら、何の話？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: [
        "あ、レイナ様。","こいつら、訓練が物足りないって言ってて、もっと厳しくしてくださいってお願いしようかと思ってたんですよ。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_MAGICIAN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "魔導兵",
      message: ["待て、言ってない言ってない。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "レイナ",
      message: [
        "あらそう？うちの兵もなんだか物足りなさそうだったから、あなたに相談しようと思ってたところなの。",
      ],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
      talker: "補助兵",
      message: ["足りてる足りてる。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["じゃあどっちの兵が最後まで立ってられるか、競ってみますか？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "レイナ",
      message: ["面白そうね。そうしましょう。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      talker: "騎士兵",
      message: ["やばい流れになってきた。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_DEFENDER,
      talker: "守護兵",
      message: ["もう無理。諦める。"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "ザーグ",
      message: ["はっはっは。お前ら、負けたら覚悟しろよ？"],
    },
    {
      background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
      left: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_SOLDIER,
      right: WIL_IMAGE_ID.CHARACTER_HOLY_KNIGHTS_LEADER,
      talker: "騎士兵",
      message: ["嫌だ！俺は死にたくない！"],
    },
  ],
];
