import { WilTalkDefine } from "@/composables/games/wil/defines/talks/index";
import { WIL_IMAGE_ID } from "@/composables/games/wil/enums/image";
import { WIL_SOUND_ID } from "@/composables/games/wil/enums/sound";

export const WIL_SUB_TALK_DEFINES_ICICLE_GURDIANS_QUEEN: Array<WilTalkDefine> =
  [
    [
      {
        background: WIL_IMAGE_ID.BACKGROUND_BLACK,
        talker: "サブイベント",
        message: ["真面目にやりなさい！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        bgm: WIL_SOUND_ID.BGM_VILLAGE1,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["もっと機敏に動きなさい！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "補助兵",
        message: ["老体には堪えるのぉ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["だから、あなた20代でしょ？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "補助兵",
        message: [
          "20代でも堪えるものは堪えるの。レイナ様は若くてうらやましいのぉ。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["魔法の勉強に勤しむのもいいけど、ちゃんと体も動かしなさい。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "補助兵",
        message: ["ヒカル君、ちょっといいかな？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["何でしょうか？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "補助兵",
        message: [
          "レイナ様はああ見えて昔は泣き虫でねぇ。よく魔法に失敗してはフロリア王様に泣きついていたんだよ。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN_SHY,
        talker: "レイナ",
        message: ["なんで今そんな話するのよ！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN_SHY,
        talker: "ヒカル",
        message: ["レイナさん、そんなかわいい一面があったんですね。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "補助兵",
        message: [
          "その後悔しくなって、わしに魔法を教えてくれとよくねだりに来たもんじゃ。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "ヒカル",
        message: ["それでこんなに魔法を使えるんですね。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "補助兵",
        message: [
          "それが今じゃ、老体のわしにもっと機敏に動けと言うようになってしもうた...。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ヒカル",
        message: ["レイナさん、少し手加減してあげた方が良いんじゃないですか？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: [
          "ヒカル、騙されないで。そいつはまだ20代なの。全然老体じゃないのよ。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "補助兵",
        message: ["あーあ、もう少しで楽できそうだったのに。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_MAGICIAN,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["もう、真面目にやりなさい！"],
      },
    ],
    [
      {
        background: WIL_IMAGE_ID.BACKGROUND_BLACK,
        talker: "サブイベント",
        message: ["冷たい氷も熱くなる"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        bgm: WIL_SOUND_ID.BGM_VILLAGE1,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["ジョット、次はどこを片付ければいいかしら？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ジョット",
        message: [
          "悪いな、手伝ってもらっちゃって。",
          "そうだな...城壁の周りの瓦礫をどかしたいかな...。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["分かったわ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ヒカル",
        message: [
          "あ、レイナさん、俺がやってた書類の整理と代わってくれますか？",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["いいけど、どうして？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ヒカル",
        message: ["瓦礫って重いし、汚れちゃうじゃないですか。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: [
          "あら、女だからって気を遣ってるの？別に、訓練だと思えばこれくらいなんともないわ。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ヒカル",
        message: [
          "いつも訓練でお世話になってますから。これくらい任せてください。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["あらそう。じゃあ任せるわ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_CASTLE,
        message: ["数時間後"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["あら、ヒカル。そっちの作業はもう終わったの？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ヒカル",
        message: [
          "はい。思ったより片付いてたので、すぐ終わりました。レイナさんの方も片付きましたか？",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["ええ。おかげさまでだいぶ楽できたわ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ヒカル",
        message: ["あれ、指から血が出てますよ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["ああ、さっき紙で切っちゃったのよ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ヒカル",
        message: ["手当てするのでちょっと見せてください。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["これくらい大丈夫よ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ヒカル",
        message: ["そう言わずに。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN_SHY,
        talker: "レイナ",
        message: ["..."],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN_SHY,
        talker: "ヒカル",
        message: ["これでよし！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN_SHY,
        talker: "レイナ",
        message: ["...い、いつまで手を握ってるのよ！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN_SHY,
        talker: "ヒカル",
        message: [
          "あ、すみません。でも、レイナさんの手って意外と暖かいんですね。氷の国の王女様だから冷たいのかと思ってました。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_STORM_LAND_INSIDE,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN_SHY,
        talker: "レイナ",
        message: ["も、もういいから！早く作業に戻るわよ！"],
      },
    ],
    [
      {
        background: WIL_IMAGE_ID.BACKGROUND_BLACK,
        talker: "サブイベント",
        message: ["親バカ"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        bgm: WIL_SOUND_ID.BGM_VILLAGE1,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: [
          "ヒカル、あなたも強くなったわね。私たちと模擬戦をやった頃とは見違えるほどよ。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "ヒカル",
        message: [
          "いえ、まだまだレイナさんには敵いません。",
          "レイナさんは昔から剣術を習ってたんですよね？少し教えてもらえませんか？",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["いいわ。まず剣を下手に構えて..."],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "フロリア王",
        message: ["じー。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "ジョット",
        message: ["何見てるんすか？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "フロリア王",
        message: ["娘に、娘に悪い虫がついておる！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "ジョット",
        message: ["悪い虫って...。ヒカルは良い奴ですよ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "フロリア王",
        message: ["しかし、あんなに密着して...。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "ジョット",
        message: ["剣術を教えてるみたいですからね。仕方ないんじゃないすか。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "レイナ",
        message: ["お父様、どうかされましたか？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "ジョット",
        message: ["あ、気づかれた。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "フロリア王",
        message: ["いや、レイナが心配でな。少し見回ってたところなんじゃ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "ヒカル",
        message: ["フロリア王、レイナさんは俺が守るので安心してください。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_HERO,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "フロリア王",
        message: ["なんじゃ、恋人面しおって！", "わしの娘は誰にもやらんぞ！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_HERO_WORRIERED,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "ヒカル",
        message: ["え？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN_SHY,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "レイナ",
        message: ["ちょっとお父様、何を仰っているのですか！？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN_SHY,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "フロリア王",
        message: ["わしの可愛い娘は誰にもやらんのじゃ！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "ジョット",
        message: ["心配しなくても、そんな強気な女、誰もらないですよ。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_STORM_SHOOTERS_PRINCE,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "フロリア王",
        message: ["わしの娘をいらんなどと言うふとどき者は許さん！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_ICE_LAND_KING,
        talker: "レイナ",
        message: ["お父様、その親バカ直してください...。"],
      },
    ],
    [
      {
        background: WIL_IMAGE_ID.BACKGROUND_BLACK,
        talker: "サブイベント",
        message: ["先王の無念を晴らす"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        bgm: WIL_SOUND_ID.BGM_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        talker: "レイナ",
        message: ["お父様...。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: [
          "レイナさん、大丈夫...じゃないですよね。何か俺の力になれることはありますか？",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "レイナ",
        message: [
          "ヒカル...。ごめんなさい、少しだけ話し相手になってくれるかしら？",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["...はい。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "レイナ",
        message: [
          "お父様はああ見えて偉大な人だったのよ。",
          "いつも私や国のことを一番に考えてくれて...。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "レイナ",
        message: [
          "氷の国は、吹雪の日が多くて、そのせいで国全体が暗いことが多かったの。",
          "でも、国民の気持ちまで暗くならないようにって、みんなを笑わせて回ってたの。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["そうなんですか。そんな一面が...。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "レイナ",
        message: [
          "きっと、お父様が亡くなったのは、最後まで敵に宝物庫の場所を教えなかったからだわ。",
          "世界を守るために、命を懸けて秘密を守ったの。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["..."],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "レイナ",
        message: [
          "私は、そんなお父様の思いを無駄にして、敵を宝物庫まで案内してしまった...。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["それは...。敵が一枚上手で、仕方なかったことで...。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "レイナ",
        message: [
          "敵が上手だったで済ませてしまえば、もし魔王が復活して世界が終わる時にも、敵が上手だったで済ませてしまうことになるわ...。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["..."],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "レイナ",
        message: [
          "だからこそ、私がお父様の...世界を、国民を守れなかったという無念を...",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "レイナ",
        message: ["絶対に晴らすわ！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "レイナ",
        message: ["ヒカル、話を聞いてくれてありがとう。","必ず、世界を救うわよ！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_ICICLE_GURDIANS_QUEEN,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "ヒカル",
        message: ["...はい！"],
      },
    ],
  ];
