import { WilTalkDefine } from "@/composables/games/wil/defines/talks/index";
import { WIL_IMAGE_ID } from "@/composables/games/wil/enums/image";
import { WIL_SOUND_ID } from "@/composables/games/wil/enums/sound";

export const WIL_SUB_TALK_DEFINES_INFERNITY_SAMURAIS_THUNDER_SPY: Array<WilTalkDefine> =
  [
    [
      {
        background: WIL_IMAGE_ID.BACKGROUND_BLACK,
        talker: "サブイベント",
        message: ["命の恩人"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        bgm: WIL_SOUND_ID.BGM_VILLAGE1,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: ["じー。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_WORRIERED,
        talker: "ヒカル",
        message: ["えーと、どうしたの？シノブちゃん。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_WORRIERED,
        talker: "シノブ",
        message: ["いえ、なんでもないです。気にしないでください。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "ヒカル",
        message: ["そう？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "シノブ",
        message: ["じー。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_WORRIERED,
        talker: "ヒカル",
        message: ["ずっと見られてると気になるんだけど...。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_WORRIERED,
        talker: "シノブ",
        message: ["すみません...。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "ヒカル",
        message: ["何か悩みがあるなら聞くよ？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "シノブ",
        message: [
          "...。",
          "実はどうやって恩を返そうか考えていたところでして。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["恩？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: [
          "私はあなたに庇われていなければとっくにこの世にいませんでした。なので、どうにかしてこの恩を返せないかと考えてまして。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: [
          "そんな、あれは俺が勝手にやったことだし、気にしなくていいよ。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: [
          "そうはいきません。恩義は必ず返せと兄様からも教えられてきたので。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["じゃあ一つ約束を守ってほしんだけど、それでいい？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: ["分かりました。何なりと。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: [
          "これからは命を大事にすること。",
          "簡単に殺すとか言わないでね。勿論、シノブちゃんが命を懸けるようなこともできるだけしないこと。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: ["それだけですか？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["それだけ。でも大事なことだから、絶対に守ってね。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: ["分かりました。命の恩人からの命令なら、命を懸けて守ります。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_ICE_LAND,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_WORRIERED,
        talker: "ヒカル",
        message: ["だから、簡単に命を懸けちゃダメなんだって...。"],
      },
    ],
    [
      {
        background: WIL_IMAGE_ID.BACKGROUND_BLACK,
        talker: "サブイベント",
        message: ["兄様"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        bgm: WIL_SOUND_ID.BGM_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        talker: "シノブ",
        message: ["兄様、申し訳ありません...。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["シノブちゃん、兄様って...。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: ["聞かれてしまいましたか...。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["もしかして、氷の国で会った忍のこと？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: ["はい。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["お兄さんはどんな人なの？"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: [
          "兄様は私と違って、強くて賢いお方なのです。",
          "正直、私が出世できたのも兄様のコネあってのことでしょう。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "ヒカル",
        message: ["お兄さんのこと、慕ってるんだね。"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "シノブ",
        message: [
          "でも、もう会いに行くことはできません。帰ってくるなとも言われました...。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: ["..."],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: [
          "焔の国と戦うなら、兄様との戦いは避けられません。",
          "兄様と相対したとき、私は刃を向けることができるのか...。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: [
          "俺はシノブちゃんと戦った時、人と人とが殺し合いをするなんて間違ってるって思ったんだ。だからシノブちゃんを助けた。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: [
          "だから、シノブちゃんのお兄さんも、できることなら殺さずに倒したい。",
          "そのために、シノブちゃんの力を貸してくれないかな。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: [
          "殺さずに倒す...。",
          "兄様も、殿様もそんなに甘くないですよ。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "ヒカル",
        message: [
          "分かってる。",
          "だから鍛えるんだ。",
          "殺さないという選択肢を選べるだけの強さを手に入れるために。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO,
        talker: "シノブ",
        message: [
          "あなたは本当にお人好しですね。",
          "私も、兄様とまた暮らせるなら、そのために強くなります。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "ヒカル",
        message: ["...うん！"],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_SMILE,
        talker: "シノブ",
        message: [
          "うかうかしてると、あなたも倒しちゃうので、覚悟してください。",
        ],
      },
      {
        background: WIL_IMAGE_ID.BACKGROUND_HOLY_LAND_SHODDY_OUTSIDE_NIGHT,
        left: WIL_IMAGE_ID.CHARACTER_INFERNITY_SAMURAIS_THUNDER_SPY,
        right: WIL_IMAGE_ID.CHARACTER_HERO_WORRIERED,
        talker: "ヒカル",
        message: ["えぇ...。"],
      },
    ],
  ];
