export enum WIL_CHARACTER_ID {
  // 聖騎士団
  HERO = "HERO",
  HOLY_KNIGHTS_LEADER = "HOLY_KNIGHTS_LEADER",
  HOLY_KNIGHTS_SOLDIER = "HOLY_KNIGHTS_SOLDIER",
  HOLY_KNIGHTS_MAGICIAN = "HOLY_KNIGHTS_MAGICIAN",

  // 氷の守護者
  ICICLE_GURDIANS_QUEEN = "ICICLE_GURDIANS_QUEEN",
  ICICLE_GURDIANS_DEFENDER = "ICICLE_GURDIANS_DEFENDER",
  ICICLE_GURDIANS_MAGICIAN = "ICICLE_GURDIANS_MAGICIAN",

  // 嵐の射手
  STORM_SHOOTERS_PRINCE = "STORM_SHOOTERS_PRINCE",
  STORM_SHOOTERS_ARCHER = "STORM_SHOOTERS_ARCHER",

  // MLSL
  SMOG_LABORATORY_MEMBER = "SMOG_LABORATORY_MEMBER",
  SMOG_LABORATORY_ANDROID = "SMOG_LABORATORY_ANDROID",

  // 獄炎武士団
  INFERNITY_SAMURAIS_KING = "INFERNITY_SAMURAIS_KING",
  INFERNITY_SAMURAIS_SAND_SPY = "INFERNITY_SAMURAIS_SAND_SPY",
  INFERNITY_SAMURAIS_THUNDER_SPY = "INFERNITY_SAMURAIS_THUNDER_SPY",
  INFERNITY_SAMURAIS_WATER_SOLDIER = "INFERNITY_SAMURAIS_WATER_SOLDIER",
  INFERNITY_SAMURAIS_WIND_SOLDIER = "INFERNITY_SAMURAIS_WIND_SOLDIER",

  // 暗黒の魔物
  DARK_MONSTER_SHADOW = "DARK_MONSTER_SHADOW",
  DARK_MONSTER_RABBIT = "DARK_MONSTER_RABBIT",
  DARK_MONSTER_UNDEAD = "DARK_MONSTER_UNDEAD",
  DARK_MONSTER_SCORPION = "DARK_MONSTER_SCORPION",
  DARK_MONSTER_LIZARD = "DARK_MONSTER_LIZARD",
  DARK_MONSTER_WATER_SOLDIER = "DARK_MONSTER_WATER_SOLDIER",
  DARK_MONSTER_THUNDER_SOLDIER = "DARK_MONSTER_THUNDER_SOLDIER",
  DARK_MONSTER_ICE_DEMON = "DARK_MONSTER_ICE_DEMON",
  DARK_MONSTER_FIRE_DEMON = "DARK_MONSTER_FIRE_DEMON",
  DARK_MONSTER_WIND_DEMON = "DARK_MONSTER_WIND_DEMON",
  DARK_MONSTER_SOIL_DEMON = "DARK_MONSTER_SOIL_DEMON",
  DARK_MONSTER_SATAN = "DARK_MONSTER_SATAN",
  DARK_MONSTER_SUPER_SATAN_HEAD = "DARK_MONSTER_SUPER_SATAN_HEAD",
  DARK_MONSTER_SUPER_SATAN_RIGHT_HAND = "DARK_MONSTER_SUPER_SATAN_RIGHT_HAND",
  DARK_MONSTER_SUPER_SATAN_LEFT_HAND = "DARK_MONSTER_SUPER_SATAN_LEFT_HAND",
  DARK_MONSTER_SUPER_SATAN_RIGHT_FOOT = "DARK_MONSTER_SUPER_SATAN_RIGHT_FOOT",
  DARK_MONSTER_SUPER_SATAN_LEFT_FOOT = "DARK_MONSTER_SUPER_SATAN_LEFT_FOOT",
}
