export enum WIL_CHARACTER_ID {
  HERO = "HERO",
  HOLY_KNIGHTS_LEADER = "HOLY_KNIGHTS_LEADER",
  HOLY_KNIGHTS_SOLDIER = "HOLY_KNIGHTS_SOLDIER",
  HOLY_KNIGHTS_MAGICIAN = "HOLY_KNIGHTS_MAGICIAN",
  HOLY_KNIGHTS_ARCHER = "HOLY_KNIGHTS_ARCHER",
}
