export enum WIL_CHARACTER_ID {
  // 聖騎士団
  HERO = "HERO",
  HOLY_KNIGHTS_LEADER = "HOLY_KNIGHTS_LEADER",
  HOLY_KNIGHTS_SOLDIER = "HOLY_KNIGHTS_SOLDIER",
  HOLY_KNIGHTS_MAGICIAN = "HOLY_KNIGHTS_MAGICIAN",

  // 氷の守り人
  ICICLE_GURDIANS_QUEEN = "ICICLE_GURDIANS_QUEEN",
  ICICLE_GURDIANS_DEFENDER = "ICICLE_GURDIANS_DEFENDER",
  ICICLE_GURDIANS_MAGICIAN = "ICICLE_GURDIANS_MAGICIAN",

  // 嵐の射手団
  STORM_SHOOTERS_PRINCE = "STORM_SHOOTERS_PRINCE",
  STORM_SHOOTERS_ARCHER = "STORM_SHOOTERS_ARCHER",
  STORM_SHOOTERS_STONE = "STORM_SHOOTERS_STONE",

  // 毒の科学研究団
  SMOG_LABORATORY_DOCTOR = "SMOG_LABORATORY_DOCTOR",
  SMOG_LABORATORY_RESEARCHER = "SMOG_LABORATORY_MEMBER",
  SMOG_LABORATORY_ANDROID = "SMOG_LABORATORY_ANDROID",

  // 焔の武士団
  INFERNITY_SAMURAIS_KING = "INFERNITY_SAMURAIS_KING",
  INFERNITY_SAMURAIS_SAND_SPY = "INFERNITY_SAMURAIS_SAND_SPY",
  INFERNITY_SAMURAIS_LIGHTNING_SPY = "INFERNITY_SAMURAIS_LIGHTNING_SPY",
  INFERNITY_SAMURAIS_WATER_SOLDIER = "INFERNITY_SAMURAIS_WATER_SOLDIER",
  INFERNITY_SAMURAIS_WIND_SOLDIER = "INFERNITY_SAMURAIS_WIND_SOLDIER",

  // 暗黒の魔物
  // 1章
  DARK_MONSTER_SHADOW = "DARK_MONSTER_SHADOW",

  // 2章
  DARK_MONSTER_RABBIT = "DARK_MONSTER_RABBIT",
  DARK_MONSTER_DEAR = "DARK_MONSTER_DEAR",

  // 3章
  DARK_MONSTER_BIRD = "DARK_MONSTER_BIRD",
  DARK_MONSTER_SCORPION = "DARK_MONSTER_SCORPION",
  DARK_MONSTER_LIZARD = "DARK_MONSTER_LIZARD",

  // 5章
  DARK_MONSTER_BATAFLY = "DARK_MONSTER_BATAFLY",
  DARK_MONSTER_BEE = "DARK_MONSTER_BEE",
  DARK_MONSTER_BEETLE = "DARK_MONSTER_BEETLE",
  DARK_MONSTER_DEMON = "DARK_MONSTER_DEMON",
  DARK_MONSTER_SATAN = "DARK_MONSTER_SATAN",
}
