export enum WIL_IMAGE_ID {
  CHARACTER_HERO = "CHARACTER_HERO",
  CHARACTER_OTHER = "CHARACTER_OTHER",
  MINI_CHARACTER_HERO = "MINI_CHARACTER_HERO",
  TRAINING_ATTACK = "TRAINING_ATTACK",
  TRAINING_DEFENSE = "TRAINING_DEFENSE",
  TRAINING_MIGRATION = "TRAINING_MIGRATION",
  TRAINING_MAGIC = "TRAINING_MAGIC",
  TRAINING_PHISIC = "TRAINING_PHISIC",
  BACKGROUND_KINGDOM = "BACKGROUND_KINGDOM",
}
