export enum WIL_SOUND_ID {
  SE_FIGHTING = "SE_FIGHTING",
  SE_GARD = "SE_GARD",
  SE_MONSTER = "SE_MONSTER",
  SE_SLASH = "SE_SLASH",

  BGM_VILLAGE_1 = "BGM_VILLAGE_1",
  BGM_PINCH_1 = "BGM_PINCH_1",
  BGM_HOLY_CASLE_1 = "BGM_HOLY_CASLE_1",
  BGM_DEPLOY_1 = "BGM_DEPLOY_1",
  BGM_BATTLE_1 = "BGM_BATTLE_1",
}
