export enum WIL_OVERALL_TIMMING {
  TITLE,
  LOADING,
  MAIN,
  ENDING,
}

export enum WIL_CHAPTER_TIMMING {
  OPENING,
  TALK,
  BATTLE,
  TRAINING,
  TEAM,
  SAVE,
  ENDING,
}

export enum WIL_BATTLE_TIMMING {
  SET_SELECT_CELL = "SET_SELECT_CELL",
  SET_SELECT_CHARACTER = "SET_SELECT_CHARACTER",

  BATTLE_START = "BATTLE_START",
  BATTLE_TURN_START = "BATTLE_TURN_START",
  BATTLE_SELECT_MOVE = "BATTLE_SELECT_MOVE",
  BATTLE_SELECT_MIGRATE_PLACE = "BATTLE_SELECT_MIGRATE_PLACE",
  BATTLE_SELECT_SKILL = "BATTLE_SELECT_SKILL",
  BATTLE_SELECT_SKILL_TARGET = "BATTLE_SELECT_SKILL_TARGET",
  BATTLE_PROCESS_MOVE = "BATTLE_PROCESS_MOVE",
  BATTLE_TURN_END = "BATTLE_TURN_END",

  BATTLE_END = "BATTLE_END",
}
