export enum WIL_FLOW_TIMMING {
  TITLE,
  MAIN,
  ENDING,
}

export enum WIL_EVENT_TIMMING {
  LOADING,
  OPENING,
  TALK,
  BATTLE,
  TRAINING,
}

export enum WIL_BATTLE_TIMMING {
  SET_SELECT_CELL = "SET_SELECT_CELL",
  SET_SELECT_CHARACTER = "SET_SELECT_CHARACTER",

  BATTLE_START = "BATTLE_START",
  BATTLE_PLAYER_TURN_START = "BATTLE_PLAYER_TURN_START",
  BATTLE_ENEMY_TURN_START = "BATTLE_ENEMY_TURN_START",

  BATTLE_SELECT_CHARACTER = "BATTLE_SELECT_CHARACTER",
  BATTLE_SELECT_MOVE = "BATTLE_SELECT_MOVE",
  BATTLE_SELECT_MIGRATE_PLACE = "BATTLE_SELECT_MIGRATE_PLACE",
  BATTLE_SELECT_SKILL = "BATTLE_SELECT_SKILL",
  BATTLE_SELECT_SKILL_TARGET = "BATTLE_SELECT_SKILL_TARGET",
  BATTLE_PROCESS_PLAYER_CHARACTER = "BATTLE_PROCESS_PLAYER_CHARACTER",
  BATTLE_PROCESS_ENEMY_CHARACTER = "BATTLE_PROCESS_ENEMY_CHARACTER",

  BATTLE_END = "BATTLE_END",
  TALK = "TALK",
}
